# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.core.fields
import apps.inventory.models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "default_income_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "default_inventory_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="inventory.itemcategory",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_item_category",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("inventory", "Inventory item"),
                            ("service", "Service"),
                            ("non_inventory", "Non-inventory item"),
                        ],
                        db_index=True,
                        default="inventory",
                        max_length=16,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "sales_price",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "purchase_price",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("track_inventory", models.BooleanField(default=True)),
                (
                    "reorder_point",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "reorder_quantity",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "valuation_method",
                    models.CharField(
                        choices=[
                            ("fifo", "First in, first out"),
                            ("weighted_average", "Weighted average cost"),
                            ("standard", "Standard cost"),
                        ],
                        default="weighted_average",
                        max_length=20,
                    ),
                ),
                ("allow_negative_stock", models.BooleanField(default=False)),
                ("barcode", models.CharField(blank=True, max_length=64)),
                (
                    "weight",
                    apps.core.fields.QuantityField(
                        blank=True, default=Decimal("0.000000"), null=True
                    ),
                ),
                ("is_batch_tracked", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cogs_items",
                        to="accounting.account",
                    ),
                ),
                (
                    "income_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="income_items",
                        to="accounting.account",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="accounting.account",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="accounting.taxrate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.itemcategory",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_item",
                "ordering": ["sku"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=120)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "is_purchase_list",
                    models.BooleanField(
                        default=False,
                        help_text="Supplier price list rather than a sales one.",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                (
                    "effective_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_price_list",
                "ordering": ["-priority", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit_price",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "discount_percent",
                    apps.core.fields.RateField(default=Decimal("0.000000")),
                ),
                ("is_percentage", models.BooleanField(default=False)),
                (
                    "min_quantity",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_rows",
                        to="inventory.item",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.pricelist",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_price_list_item",
                "ordering": ["item", "-min_quantity"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                (
                    "adjustment_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("count", "Physical count variance"),
                            ("damage", "Damage"),
                            ("theft", "Theft / shrinkage"),
                            ("expiry", "Expiry"),
                            ("revaluation", "Revaluation"),
                            ("opening", "Opening balance"),
                            ("other", "Other"),
                        ],
                        default="count",
                        max_length=12,
                    ),
                ),
                ("memo", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "total_value_delta",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_adjustments",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stock_adjustment",
                "ordering": ["-adjustment_date", "-created_at"],
                "abstract": False,
            },
            bases=(apps.inventory.models.StatusTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_number", models.CharField(max_length=64)),
                (
                    "quantity_received",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "quantity_remaining",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("unit_cost", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                ("manufactured_on", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("supplier_reference", models.CharField(blank=True, max_length=100)),
                ("is_quarantined", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="inventory.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stock_batch",
                "ordering": ["expires_on", "received_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockAdjustmentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveSmallIntegerField()),
                (
                    "quantity_expected",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "quantity_counted",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "quantity_delta",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("unit_cost", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "value_delta",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockadjustment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.stockbatch",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stock_adjustment_line",
                "ordering": ["adjustment", "line_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=80)),
                ("symbol", models.CharField(blank=True, max_length=12)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unit", "Discrete unit"),
                            ("weight", "Weight"),
                            ("volume", "Volume"),
                            ("length", "Length"),
                            ("area", "Area"),
                            ("time", "Time"),
                        ],
                        default="unit",
                        max_length=10,
                    ),
                ),
                ("conversion_factor", apps.core.fields.RateField(default=1)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "base_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived",
                        to="inventory.unitofmeasure",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_unit_of_measure",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="item",
            name="uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("address", models.TextField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_warehouse",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase receipt"),
                            ("sale", "Sale / delivery"),
                            ("return_in", "Customer return"),
                            ("return_out", "Return to vendor"),
                            ("adjustment", "Stock adjustment"),
                            ("transfer_in", "Transfer in"),
                            ("transfer_out", "Transfer out"),
                            ("production", "Production"),
                            ("opening", "Opening balance"),
                        ],
                        db_index=True,
                        max_length=14,
                    ),
                ),
                (
                    "quantity_delta",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("unit_cost", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "total_cost",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "running_quantity_after",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "running_value_after",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stockbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.item",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stock_movement",
                "ordering": ["-occurred_at", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_on_hand",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "quantity_reserved",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "quantity_available",
                    apps.core.fields.QuantityField(
                        db_index=True, default=Decimal("0.000000")
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "average_cost",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "total_value",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("last_movement_at", models.DateTimeField(blank=True, null=True)),
                ("last_counted_at", models.DateTimeField(blank=True, null=True)),
                ("allow_negative", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_levels",
                        to="inventory.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_levels",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stock_level",
                "ordering": ["item", "warehouse"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments",
                to="inventory.warehouse",
            ),
        ),
        migrations.CreateModel(
            name="LowStockAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "threshold_at_trigger",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "quantity_at_trigger",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                (
                    "triggered_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="low_stock_alerts",
                        to="inventory.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="low_stock_alerts",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_low_stock_alert",
                "ordering": ["-triggered_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_i_tenant__240901_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["tenant", "parent"], name="ix_item_category_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemcategory",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_item_category_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="ck_item_category_no_self_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="pricelist",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_p_tenant__f823bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricelist",
            index=models.Index(
                fields=["tenant", "is_active", "effective_from"],
                name="ix_price_list_effective",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelist",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_price_list_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("tenant", "currency", "is_purchase_list"),
                name="uq_price_list_one_default",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelist",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_price_list_date_order",
            ),
        ),
        migrations.AddIndex(
            model_name="pricelistitem",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_p_tenant__1be069_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricelistitem",
            index=models.Index(
                fields=["tenant", "item", "is_active"], name="ix_price_item_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="pricelistitem",
            index=models.Index(
                fields=["price_list", "item"], name="ix_price_item_list"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.UniqueConstraint(
                fields=("price_list", "item", "min_quantity", "effective_from"),
                name="uq_price_list_item_break",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0), ("min_quantity__gte", 0)),
                name="ck_price_list_item_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_percent__gte", 0), ("discount_percent__lte", 1)
                ),
                name="ck_price_list_item_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_from__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_price_list_item_date_order",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustmentline",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_s_tenant__0d0547_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustmentline",
            index=models.Index(
                fields=["tenant", "item"], name="ix_stock_adj_line_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustmentline",
            constraint=models.UniqueConstraint(
                fields=("adjustment", "line_number"), name="uq_stock_adj_line_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustmentline",
            constraint=models.UniqueConstraint(
                fields=("adjustment", "item", "batch"), name="uq_stock_adj_line_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "quantity_delta",
                        django.db.models.expressions.CombinedExpression(
                            models.F("quantity_counted"),
                            "-",
                            models.F("quantity_expected"),
                        ),
                    )
                ),
                name="ck_stock_adj_line_delta",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="ck_stock_adj_line_cost_non_neg",
            ),
        ),
        migrations.AddIndex(
            model_name="unitofmeasure",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_u_tenant__e38feb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitofmeasure",
            index=models.Index(fields=["tenant", "is_active"], name="ix_uom_active"),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_uom_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.CheckConstraint(
                condition=models.Q(("conversion_factor__gt", 0)),
                name="ck_uom_factor_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_uom", models.F("id")), _negated=True),
                name="ck_uom_no_self_base",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.CheckConstraint(
                condition=models.Q(("decimal_places__lte", 6)),
                name="ck_uom_precision_within_column",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_i_tenant__b16890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["tenant", "type", "is_active"], name="ix_item_type"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["tenant", "category"], name="ix_item_category"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["tenant", "name"], name="ix_item_name"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["tenant", "track_inventory", "is_active"],
                name="ix_item_tracked",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sku"), name="uq_item_sku"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("tenant", "barcode"),
                name="uq_item_barcode",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "service"), _negated=True),
                    models.Q(
                        ("track_inventory", False), ("inventory_account__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="ck_item_service_not_stocked",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("track_inventory", False),
                    ("inventory_account__isnull", False),
                    _connector="OR",
                ),
                name="ck_item_tracked_needs_inv_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("sales_price__gte", 0), ("purchase_price__gte", 0)),
                name="ck_item_prices_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reorder_point__gte", 0), ("reorder_quantity__gte", 0)
                ),
                name="ck_item_reorder_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_w_tenant__f69351_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["tenant", "is_active"], name="ix_warehouse_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_warehouse_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("tenant",),
                name="uq_warehouse_one_default",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_s_tenant__f5ad82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "item", "warehouse", "occurred_at"],
                name="ix_stock_movement_bin",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "movement_type", "occurred_at"],
                name="ix_stock_movement_type",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="ix_stock_movement_source",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "batch"], name="ix_stock_movement_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_stock_movement_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_delta", 0), _negated=True),
                name="ck_stock_movement_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0), ("total_cost__gte", 0)),
                name="ck_stock_movement_cost_non_neg",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("movement_type__in", ["purchase", "return_in", "transfer_in"]),
                        _negated=True,
                    ),
                    ("quantity_delta__gt", 0),
                    _connector="OR",
                ),
                name="ck_stock_movement_inbound_sign",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("movement_type__in", ["sale", "return_out", "transfer_out"]),
                        _negated=True,
                    ),
                    ("quantity_delta__lt", 0),
                    _connector="OR",
                ),
                name="ck_stock_movement_outbound_sign",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklevel",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_s_tenant__c8a801_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocklevel",
            index=models.Index(fields=["tenant", "item"], name="ix_stock_level_item"),
        ),
        migrations.AddIndex(
            model_name="stocklevel",
            index=models.Index(
                fields=["tenant", "warehouse"], name="ix_stock_level_warehouse"
            ),
        ),
        migrations.AddIndex(
            model_name="stocklevel",
            index=models.Index(
                fields=["tenant", "quantity_available"], name="ix_stock_level_low"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.UniqueConstraint(
                fields=("tenant", "item", "warehouse"), name="uq_stock_level_bin"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_reserved__gte", 0)),
                name="ck_stock_level_reserved_non_neg",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allow_negative", True),
                    ("quantity_on_hand__gte", 0),
                    _connector="OR",
                ),
                name="ck_stock_level_on_hand_non_neg",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "quantity_available",
                        django.db.models.expressions.CombinedExpression(
                            models.F("quantity_on_hand"),
                            "-",
                            models.F("quantity_reserved"),
                        ),
                    )
                ),
                name="ck_stock_level_available_derived",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("average_cost__gte", 0)),
                name="ck_stock_level_cost_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_s_tenant__0c3b5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["tenant", "item", "expires_on"], name="ix_stock_batch_fefo"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["tenant", "warehouse", "item"], name="ix_stock_batch_bin"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "item", "warehouse", "batch_number"),
                name="uq_stock_batch_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_remaining__gte", 0), ("quantity_received__gte", 0)
                ),
                name="ck_stock_batch_qty_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_remaining__lte", models.F("quantity_received"))
                ),
                name="ck_stock_batch_not_over_consumed",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="ck_stock_batch_cost_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("manufactured_on__isnull", True),
                    ("expires_on__isnull", True),
                    ("expires_on__gte", models.F("manufactured_on")),
                    _connector="OR",
                ),
                name="ck_stock_batch_date_order",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_s_tenant__bd5eba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["tenant", "status", "adjustment_date"],
                name="ix_stock_adj_status",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["tenant", "warehouse"], name="ix_stock_adj_warehouse"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("tenant", "number"),
                name="uq_stock_adjustment_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "cancelled"]),
                    models.Q(
                        ("approved_by__isnull", False), ("approved_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_stock_adjustment_approver",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "posted"), _negated=True),
                    ("posted_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_stock_adjustment_posted_at",
            ),
        ),
        migrations.AddIndex(
            model_name="lowstockalert",
            index=models.Index(
                fields=["tenant", "-created_at"], name="inventory_l_tenant__3cfc7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lowstockalert",
            index=models.Index(
                fields=["tenant", "acknowledged_at"], name="ix_low_stock_open"
            ),
        ),
        migrations.AddIndex(
            model_name="lowstockalert",
            index=models.Index(fields=["tenant", "item"], name="ix_low_stock_item"),
        ),
        migrations.AddIndex(
            model_name="lowstockalert",
            index=models.Index(
                fields=["tenant", "notification_sent"], name="ix_low_stock_notify"
            ),
        ),
        migrations.AddConstraint(
            model_name="lowstockalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("acknowledged_at__isnull", True)),
                fields=("tenant", "item", "warehouse"),
                name="uq_low_stock_alert_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="lowstockalert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("acknowledged_at__isnull", True),
                    ("acknowledged_by__isnull", False),
                    _connector="OR",
                ),
                name="ck_low_stock_alert_ack_by",
            ),
        ),
        migrations.AddConstraint(
            model_name="lowstockalert",
            constraint=models.CheckConstraint(
                condition=models.Q(("occurrence_count__gte", 1)),
                name="ck_low_stock_alert_occurrences",
            ),
        ),
    ]
