# Generated by Django 5.2.17 on 2026-08-17 14:50

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountGrouping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=150)),
                (
                    "statement",
                    models.CharField(
                        choices=[
                            ("profit_loss", "Profit & loss"),
                            ("balance_sheet", "Balance sheet"),
                            ("cash_flow", "Cash flow"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_account_grouping",
                "ordering": ["statement", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable identifier used by schedules and API callers.",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("profit_loss", "Profit & loss"),
                            ("balance_sheet", "Balance sheet"),
                            ("trial_balance", "Trial balance"),
                            ("cash_flow", "Cash flow statement"),
                            ("tax_summary", "Tax summary"),
                            ("ar_aging", "Accounts receivable aging"),
                            ("ap_aging", "Accounts payable aging"),
                            ("general_ledger", "General ledger"),
                            ("payroll_register", "Payroll register"),
                            ("expense_by_category", "Expenses by category"),
                            ("inventory_valuation", "Inventory valuation"),
                            ("project_profitability", "Project profitability"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("default_parameters", models.JSONField(blank=True, default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grouping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="definitions",
                        to="reporting.accountgrouping",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_definition",
                "ordering": ["report_type", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportLineMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=150)),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                ("level", models.PositiveSmallIntegerField(default=0)),
                (
                    "account_type",
                    models.CharField(blank=True, db_index=True, max_length=12),
                ),
                ("code_from", models.CharField(blank=True, max_length=20)),
                ("code_to", models.CharField(blank=True, max_length=20)),
                ("system_key", models.CharField(blank=True, max_length=50)),
                ("sign", models.SmallIntegerField(default=1)),
                ("is_subtotal", models.BooleanField(default=False)),
                (
                    "subtotal_from_sequence",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_bold", models.BooleanField(default=False)),
                ("hide_if_zero", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_line_mappings",
                        to="accounting.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grouping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="reporting.accountgrouping",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_line_mapping",
                "ordering": ["grouping", "sequence"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("cron", "Custom cron expression"),
                        ],
                        default="monthly",
                        max_length=12,
                    ),
                ),
                ("cron_expression", models.CharField(blank=True, max_length=100)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        help_text="Email addresses the rendered report is delivered to.",
                        size=None,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("xlsx", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=8,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                (
                    "consecutive_failure_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="reporting.reportdefinition",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_schedule",
                "ordering": ["next_run_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("profit_loss", "Profit & loss"),
                            ("balance_sheet", "Balance sheet"),
                            ("trial_balance", "Trial balance"),
                            ("cash_flow", "Cash flow statement"),
                            ("tax_summary", "Tax summary"),
                            ("ar_aging", "Accounts receivable aging"),
                            ("ap_aging", "Accounts payable aging"),
                            ("general_ledger", "General ledger"),
                            ("payroll_register", "Payroll register"),
                            ("expense_by_category", "Expenses by category"),
                            ("inventory_valuation", "Inventory valuation"),
                            ("project_profitability", "Project profitability"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("as_of_date", models.DateField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(db_index=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("file_key", models.CharField(blank=True, max_length=255)),
                (
                    "file_format",
                    models.CharField(
                        blank=True,
                        choices=[("pdf", "PDF"), ("xlsx", "Excel"), ("csv", "CSV")],
                        max_length=8,
                    ),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="reporting.reportdefinition",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_snapshot",
                "ordering": ["-generated_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="accountgrouping",
            index=models.Index(
                fields=["tenant", "-created_at"], name="reporting_a_tenant__41743a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountgrouping",
            index=models.Index(
                fields=["tenant", "statement", "is_active"],
                name="ix_report_grouping_stmt",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountgrouping",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_report_grouping_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountgrouping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("tenant", "statement"),
                name="uq_report_grouping_one_default",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountgrouping",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="ck_report_grouping_code_present",
            ),
        ),
        migrations.AddIndex(
            model_name="reportdefinition",
            index=models.Index(
                fields=["tenant", "-created_at"], name="reporting_d_tenant__ecc2d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportdefinition",
            index=models.Index(
                fields=["tenant", "report_type", "is_active"], name="ix_report_def_type"
            ),
        ),
        migrations.AddIndex(
            model_name="reportdefinition",
            index=models.Index(fields=["tenant", "owner"], name="ix_report_def_owner"),
        ),
        migrations.AddConstraint(
            model_name="reportdefinition",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_report_definition_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="ck_report_definition_code_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_shared", True), ("owner__isnull", False), _connector="OR"
                ),
                name="ck_report_definition_private_has_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="reportlinemapping",
            index=models.Index(
                fields=["tenant", "-created_at"], name="reporting_l_tenant__97f0c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportlinemapping",
            index=models.Index(
                fields=["tenant", "grouping", "sequence"],
                name="ix_report_mapping_group",
            ),
        ),
        migrations.AddIndex(
            model_name="reportlinemapping",
            index=models.Index(
                fields=["tenant", "account_type"], name="ix_report_mapping_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportlinemapping",
            constraint=models.UniqueConstraint(
                fields=("tenant", "grouping", "sequence"),
                name="uq_report_line_mapping_seq",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportlinemapping",
            constraint=models.CheckConstraint(
                condition=models.Q(("sign__in", [1, -1])),
                name="ck_report_line_mapping_sign",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportlinemapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_subtotal", True),
                    models.Q(("account_type", ""), _negated=True),
                    models.Q(("code_from", ""), _negated=True),
                    models.Q(("system_key", ""), _negated=True),
                    ("account__isnull", False),
                    _connector="OR",
                ),
                name="ck_report_line_mapping_selector",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportlinemapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code_to", ""),
                    ("code_from", ""),
                    ("code_to__gte", models.F("code_from")),
                    _connector="OR",
                ),
                name="ck_report_line_mapping_code_range",
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["tenant", "-created_at"], name="reporting_s_tenant__ad365c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["is_active", "next_run_at"], name="ix_report_sched_due"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["tenant", "definition"], name="ix_report_sched_definition"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportschedule",
            constraint=models.UniqueConstraint(
                fields=("tenant", "definition", "name"), name="uq_report_schedule_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_active", False), ("recipients__len__gt", 0), _connector="OR"
                ),
                name="ck_report_schedule_active_has_recipient",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_active", False),
                    ("next_run_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_report_schedule_active_has_next_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("frequency", "cron"), _negated=True),
                    models.Q(("cron_expression", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_report_schedule_cron_present",
            ),
        ),
        migrations.AddIndex(
            model_name="reportsnapshot",
            index=models.Index(
                fields=["tenant", "-created_at"], name="reporting_s_tenant__b40f49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportsnapshot",
            index=models.Index(
                fields=["tenant", "report_type", "period_start", "period_end"],
                name="ix_report_snap_type_period",
            ),
        ),
        migrations.AddIndex(
            model_name="reportsnapshot",
            index=models.Index(
                fields=["tenant", "definition", "-generated_at"],
                name="ix_report_snap_definition",
            ),
        ),
        migrations.AddIndex(
            model_name="reportsnapshot",
            index=models.Index(
                fields=["tenant", "-generated_at"], name="ix_report_snap_generated"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period_end__isnull", True),
                    ("period_start__isnull", True),
                    ("period_end__gte", models.F("period_start")),
                    _connector="OR",
                ),
                name="ck_report_snapshot_period_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("checksum", ""), _negated=True),
                name="ck_report_snapshot_has_checksum",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("as_of_date__isnull", False),
                    ("period_end__isnull", False),
                    _connector="OR",
                ),
                name="ck_report_snapshot_has_boundary",
            ),
        ),
    ]
