# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.core.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceBreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("meal", "Meal"),
                            ("prayer", "Prayer"),
                            ("rest", "Rest"),
                            ("personal", "Personal"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("is_paid", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_attendance_break",
                "ordering": ["started_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("work_date", models.DateField(db_index=True)),
                ("check_in_at", models.DateTimeField(blank=True, null=True)),
                ("check_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "worked_hours",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "overtime_hours",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("early_leave_minutes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half day"),
                            ("on_leave", "On leave"),
                            ("holiday", "Holiday"),
                            ("weekend", "Weekend"),
                        ],
                        db_index=True,
                        default="present",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual entry"),
                            ("biometric", "Biometric terminal"),
                            ("mobile_gps", "Mobile app (GPS)"),
                            ("web", "Web check-in"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("check_in_location", models.JSONField(blank=True, default=dict)),
                ("check_out_location", models.JSONField(blank=True, default=dict)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hr_attendance_record",
                "ordering": ["-work_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=150)),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Slash-delimited, slash-terminated ancestry, e.g. /root/eng/backend/",
                        max_length=500,
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_department",
                "ordering": ["path", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_code", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("arabic_name", models.CharField(blank=True, max_length=200)),
                ("national_id", models.CharField(blank=True, max_length=64)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unspecified", "Unspecified"),
                        ],
                        default="unspecified",
                        max_length=12,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("unspecified", "Unspecified"),
                        ],
                        default="unspecified",
                        max_length=12,
                    ),
                ),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("work_email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.JSONField(blank=True, default=dict)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full time"),
                            ("part_time", "Part time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("temporary", "Temporary"),
                        ],
                        db_index=True,
                        default="full_time",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On leave"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("resigned", "Resigned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                ("hire_date", models.DateField(db_index=True)),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.CharField(blank=True, max_length=255)),
                (
                    "base_salary",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                (
                    "pay_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("biweekly", "Bi-weekly"),
                            ("weekly", "Weekly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("bank_account_iban", models.CharField(blank=True, max_length=64)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("tax_id", models.CharField(blank=True, max_length=64)),
                (
                    "social_insurance_number",
                    models.CharField(blank=True, max_length=64),
                ),
                ("photo_key", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "hr_employee",
                "ordering": ["employee_code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Employment contract"),
                            ("id", "Identity document"),
                            ("certificate", "Certificate / qualification"),
                            ("visa", "Visa / work permit"),
                            ("passport", "Passport"),
                            ("medical", "Medical"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file_key", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_confidential", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "hr_employee_document",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("date", models.DateField(db_index=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_holiday",
                "ordering": ["date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=150)),
                ("grade", models.CharField(blank=True, max_length=20)),
                (
                    "min_salary",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "max_salary",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_job_title",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_order", models.PositiveSmallIntegerField(default=1)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped (no approver at this level)"),
                            ("delegated", "Delegated"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "db_table": "hr_leave_approval",
                "ordering": ["request", "step_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "opening_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "accrued_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "taken_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "carried_over_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "adjusted_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "available_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "pending_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("last_accrued_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "hr_leave_balance",
                "ordering": ["-year"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField()),
                ("half_day_start", models.BooleanField(default=False)),
                ("half_day_end", models.BooleanField(default=False)),
                (
                    "total_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("pending_manager", "Pending manager approval"),
                            ("pending_hr", "Pending HR approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("attachment_key", models.CharField(blank=True, max_length=255)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=500)),
                ("balance_applied", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "hr_leave_request",
                "ordering": ["-start_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "accrual_method",
                    models.CharField(
                        choices=[
                            ("none", "No accrual (fixed entitlement)"),
                            ("monthly", "Accrues monthly"),
                            ("annual", "Granted annually"),
                            ("per_hour_worked", "Accrues per hour worked"),
                        ],
                        default="annual",
                        max_length=16,
                    ),
                ),
                (
                    "accrual_rate_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "max_balance_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "allow_negative_balance",
                    models.BooleanField(
                        default=False,
                        help_text="Permit advancing leave the employee has not yet accrued.",
                    ),
                ),
                (
                    "carry_over_limit_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "requires_attachment_after_days",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "gender_restriction",
                    models.CharField(
                        choices=[
                            ("none", "Any"),
                            ("male", "Male only"),
                            ("female", "Female only"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                ("min_service_months", models.PositiveSmallIntegerField(default=0)),
                ("min_notice_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "affects_payroll",
                    models.BooleanField(
                        default=False,
                        help_text="True when days taken change gross pay (unpaid leave).",
                    ),
                ),
                (
                    "requires_hr_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Second approval step after the direct manager.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_leave_type",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("hire", "Initial salary on hire"),
                            ("raise", "Salary increase"),
                            ("cut", "Salary decrease"),
                            ("promotion", "Promotion"),
                            ("transfer", "Department transfer"),
                            ("correction", "Correction of a previous revision"),
                        ],
                        default="raise",
                        max_length=12,
                    ),
                ),
                ("effective_date", models.DateField(db_index=True)),
                (
                    "previous_salary",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "new_salary",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hr_salary_revision",
                "ordering": ["-effective_date", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("crosses_midnight", models.BooleanField(default=False)),
                ("break_minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "expected_hours_per_day",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "overtime_after_hours",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("late_grace_minutes", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_shift",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("working_days", models.JSONField(blank=True, default=list)),
                (
                    "expected_hours_per_week",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_work_schedule",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
    ]
