# Generated by Django 5.2.17 on 2026-08-19 14:14

import apps.core.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import rls_operations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        ('payroll', '0001_initial'),
        ('tenancy', '0003_rls_nullable_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('multiplier', apps.core.fields.RateField(default=1)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_types', to='payroll.payrollcomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_overtime_type',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OvertimeSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True)),
                ('hours', apps.core.fields.QuantityField(default=Decimal('0.000000'))),
                ('hourly_rate', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('amount', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('KWD', 'Kuwaiti Dinar')], max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], db_index=True, default='draft', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_overtime_slips', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_slips', to='hr.employee')),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_slips', to='payroll.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('overtime_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slips', to='hr.overtimetype')),
            ],
            options={
                'db_table': 'hr_overtime_slip',
                'ordering': ['-work_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='hr.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.shift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_shift_assignment',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='overtimetype',
            index=models.Index(fields=['tenant', '-created_at'], name='hr_overtime_tenant__f1f49e_idx'),
        ),
        migrations.AddConstraint(
            model_name='overtimetype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_hr_overtime_type_code'),
        ),
        migrations.AddConstraint(
            model_name='overtimetype',
            constraint=models.CheckConstraint(condition=models.Q(('multiplier__gt', 0)), name='ck_hr_overtime_multiplier_positive'),
        ),
        migrations.AddIndex(
            model_name='overtimeslip',
            index=models.Index(fields=['tenant', 'employee', '-work_date'], name='ix_hr_ot_emp_date'),
        ),
        migrations.AddIndex(
            model_name='overtimeslip',
            index=models.Index(fields=['tenant', 'status'], name='ix_hr_ot_status'),
        ),
        migrations.AddConstraint(
            model_name='overtimeslip',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gt', 0)), name='ck_hr_overtime_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='overtimeslip',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('hourly_rate__gte', 0)), name='ck_hr_overtime_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='overtimeslip',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='ck_hr_overtime_approved_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='overtimeslip',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('rejected_reason', ''), _negated=True), _connector='OR'), name='ck_hr_overtime_rejected_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='overtimeslip',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'work_date', 'overtime_type'), name='uq_hr_overtime_slip_day'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['tenant', 'employee', '-start_date'], name='ix_hr_shiftasg_emp'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='ck_hr_shift_assignment_dates'),
        ),
            *rls_operations("hr_shift_assignment", "hr_overtime_type", "hr_overtime_slip"),
    ]
