# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.core.fields
import apps.projects.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(blank=True, max_length=80)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "hourly_rate",
                    apps.core.fields.MoneyField(
                        blank=True, default=Decimal("0.000000"), null=True
                    ),
                ),
                (
                    "allocation_percent",
                    apps.core.fields.RateField(default=Decimal("0.000000")),
                ),
                (
                    "joined_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("left_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "projects_project_member",
                "ordering": ["project", "employee"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("delivered_on", models.DateField(blank=True, null=True)),
                ("accepted_on", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "percentage_of_budget",
                    apps.core.fields.RateField(default=Decimal("0.000000")),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("delivered", "Delivered, awaiting acceptance"),
                            ("accepted", "Accepted by client"),
                            ("invoiced", "Invoiced"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=12,
                    ),
                ),
                ("is_billable", models.BooleanField(default=True)),
                ("invoiced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "projects_project_milestone",
                "ordering": ["project", "sequence"],
                "abstract": False,
            },
            bases=(apps.projects.models.StatusTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "estimated_hours",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("is_billable", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("in_progress", "In progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="todo",
                        max_length=12,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "hourly_rate",
                    apps.core.fields.MoneyField(
                        blank=True, default=Decimal("0.000000"), null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "projects_project_task",
                "ordering": ["project", "sort_order", "name"],
                "abstract": False,
            },
            bases=(apps.projects.models.StatusTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("work_date", models.DateField(db_index=True)),
                ("hours", apps.core.fields.QuantityField(default=Decimal("0.000000"))),
                ("description", models.CharField(blank=True, max_length=500)),
                ("is_billable", models.BooleanField(db_index=True, default=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "billable_rate",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("cost_rate", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("invoiced", "Invoiced"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("invoiced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "projects_timesheet_entry",
                "ordering": ["-work_date", "-created_at"],
                "abstract": False,
            },
            bases=(apps.projects.models.StatusTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("on_hold", "On hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("fixed_fee", "Fixed fee"),
                            ("time_and_materials", "Time & materials"),
                            ("milestone", "Milestone"),
                            ("non_billable", "Non-billable"),
                        ],
                        db_index=True,
                        default="time_and_materials",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "budget_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "budget_hours",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "default_hourly_rate",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_billable", models.BooleanField(default=True)),
                (
                    "actual_hours",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "actual_cost_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "invoiced_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_project",
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(apps.projects.models.StatusTransitionMixin, models.Model),
        ),
    ]
