# Generated by Django 5.2.17 on 2026-08-17 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0002_initial"),
        ("projects", "0001_initial"),
        ("sales", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_projects",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_memberships",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_milestones",
                to="sales.invoice",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_tasks",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="projects.projecttask",
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timesheet_entries",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="invoice_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timesheet_entry",
                to="sales.invoiceline",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timesheet_entries",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timesheet_entries",
                to="projects.projecttask",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant", "-created_at"], name="projects_pr_tenant__5d8ad4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["tenant", "status"], name="ix_project_status"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant", "customer"], name="ix_project_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["tenant", "manager"], name="ix_project_manager"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant", "start_date", "end_date"], name="ix_project_dates"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_project_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="ck_project_date_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("budget_amount__gte", 0),
                    ("budget_hours__gte", 0),
                    ("default_hourly_rate__gte", 0),
                ),
                name="ck_project_budget_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_billable", False),
                    ("billing_type", "non_billable"),
                    ("customer__isnull", False),
                    _connector="OR",
                ),
                name="ck_project_billable_has_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("billing_type", "non_billable"), _negated=True),
                    ("is_billable", False),
                    _connector="OR",
                ),
                name="ck_project_non_billable_flag",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["tenant", "-created_at"], name="projects_pr_tenant__a6e7b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["tenant", "employee"], name="ix_project_member_emp"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["tenant", "project", "is_active"], name="ix_project_member_proj"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("project", "employee"),
                name="uq_project_member_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocation_percent__gte", 0), ("allocation_percent__lte", 1)
                ),
                name="ck_project_member_allocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hourly_rate__isnull", True),
                    ("hourly_rate__gte", 0),
                    _connector="OR",
                ),
                name="ck_project_member_rate_non_neg",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("left_on__isnull", True),
                    ("left_on__gte", models.F("joined_on")),
                    _connector="OR",
                ),
                name="ck_project_member_date_order",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(
                fields=["tenant", "-created_at"], name="projects_pr_tenant__73af9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(
                fields=["tenant", "project", "status"], name="ix_milestone_status"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(fields=["tenant", "due_date"], name="ix_milestone_due"),
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(
                fields=["tenant", "status", "is_billable"], name="ix_milestone_billable"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmilestone",
            constraint=models.UniqueConstraint(
                fields=("project", "sequence"), name="uq_milestone_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmilestone",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="ck_milestone_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmilestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("percentage_of_budget__gte", 0), ("percentage_of_budget__lte", 1)
                ),
                name="ck_milestone_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmilestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "invoiced"), _negated=True),
                    ("invoice__isnull", False),
                    _connector="OR",
                ),
                name="ck_milestone_invoiced_has_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmilestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invoice__isnull", True), ("status", "invoiced"), _connector="OR"
                ),
                name="ck_milestone_invoice_implies_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmilestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["accepted", "invoiced"]), _negated=True),
                    ("accepted_on__isnull", False),
                    _connector="OR",
                ),
                name="ck_milestone_accepted_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmilestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("accepted_on__isnull", True),
                    ("delivered_on__isnull", True),
                    ("accepted_on__gte", models.F("delivered_on")),
                    _connector="OR",
                ),
                name="ck_milestone_date_order",
            ),
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(
                fields=["tenant", "-created_at"], name="projects_pr_tenant__a5932a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(
                fields=["tenant", "project", "status"], name="ix_project_task_status"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(
                fields=["tenant", "assigned_to"], name="ix_project_task_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(
                fields=["tenant", "parent"], name="ix_project_task_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="projecttask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("project", "code"),
                name="uq_project_task_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="projecttask",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="ck_project_task_no_self_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="projecttask",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_hours__gte", 0)),
                name="ck_project_task_hours_non_neg",
            ),
        ),
        migrations.AddConstraint(
            model_name="projecttask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hourly_rate__isnull", True),
                    ("hourly_rate__gte", 0),
                    _connector="OR",
                ),
                name="ck_project_task_rate_non_neg",
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(
                fields=["tenant", "-created_at"], name="projects_ti_tenant__043e37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(
                fields=["tenant", "status", "work_date"], name="ix_timesheet_status"
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(
                fields=["tenant", "employee", "work_date"], name="ix_timesheet_employee"
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(
                fields=["tenant", "project", "work_date"], name="ix_timesheet_project"
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(
                fields=["tenant", "project", "is_billable", "status"],
                name="ix_timesheet_wip",
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(fields=["tenant", "task"], name="ix_timesheet_task"),
        ),
        migrations.AddConstraint(
            model_name="timesheetentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("hours__gt", 0), ("hours__lte", 24)),
                name="ck_timesheet_hours_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesheetentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("billable_rate__gte", 0), ("cost_rate__gte", 0)),
                name="ck_timesheet_rates_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesheetentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "invoiced"), _negated=True),
                    ("invoice_line__isnull", False),
                    _connector="OR",
                ),
                name="ck_timesheet_invoiced_has_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesheetentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invoice_line__isnull", True),
                    ("status", "invoiced"),
                    _connector="OR",
                ),
                name="ck_timesheet_line_implies_invoiced",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesheetentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "invoiced"), ("invoice_line__isnull", False)
                ),
                fields=("tenant", "invoice_line"),
                name="uq_timesheet_invoiced_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesheetentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    ("approved_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_timesheet_approved_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesheetentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_billable", True),
                    ("invoice_line__isnull", True),
                    _connector="OR",
                ),
                name="ck_timesheet_non_billable_uninvoiced",
            ),
        ),
    ]
