# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.core.fields
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("income", "Income"),
                            ("expense", "Expense"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("is_postable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "system_key",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "is_reconcilable",
                    models.BooleanField(
                        default=False,
                        help_text="Bank/cash accounts eligible for reconciliation.",
                    ),
                ),
                (
                    "cached_balance",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("cached_balance_as_of", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_account",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(max_length=50)),
                ("year", models.PositiveSmallIntegerField()),
                ("prefix", models.CharField(max_length=12)),
                ("next_value", models.PositiveIntegerField(default=1)),
                ("padding", models.PositiveSmallIntegerField(default=6)),
            ],
            options={
                "db_table": "accounting_document_sequence",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("rate", apps.core.fields.RateField(default=Decimal("0.000000"))),
                ("rate_date", models.DateField(db_index=True)),
                ("source", models.CharField(default="manual", max_length=50)),
            ],
            options={
                "db_table": "accounting_exchange_rate",
                "ordering": ["-rate_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("soft_closed", "Soft closed"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_fiscal_period",
                "ordering": ["start_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_fiscal_year",
                "ordering": ["-start_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("purchase", "Purchase"),
                            ("cash", "Cash & bank"),
                            ("payroll", "Payroll"),
                            ("inventory", "Inventory"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("sequence_prefix", models.CharField(default="JE", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "accounting_journal",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("entry_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("voided", "Voided"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("invoice", "Customer invoice"),
                            ("bill", "Vendor bill"),
                            ("payment", "Payment"),
                            ("expense", "Expense"),
                            ("payroll", "Payroll run"),
                            ("inventory", "Inventory movement"),
                            ("bank", "Bank reconciliation"),
                            ("opening", "Opening balance"),
                            ("closing", "Year-end closing"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("memo", models.CharField(blank=True, max_length=500)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("exchange_rate", apps.core.fields.RateField(default=1)),
                (
                    "total_debit",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "total_credit",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                ("source_document_type", models.CharField(blank=True, max_length=50)),
                ("source_document_id", models.UUIDField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "db_table": "accounting_journal_entry",
                "ordering": ["-entry_date", "-number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=500)),
                ("debit", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                ("credit", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "base_debit",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "base_credit",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "partner_type",
                    models.CharField(
                        blank=True,
                        help_text="customer | vendor | employee",
                        max_length=20,
                    ),
                ),
                ("partner_id", models.UUIDField(blank=True, null=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_journal_line",
                "ordering": ["entry", "line_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                (
                    "rate",
                    apps.core.fields.RateField(
                        default=Decimal("0.000000"),
                        help_text="Fraction, e.g. 0.140000 for 14%.",
                    ),
                ),
                ("is_compound", models.BooleanField(default=False)),
                (
                    "is_recoverable",
                    models.BooleanField(
                        default=True,
                        help_text="Input VAT reclaimable; otherwise expensed.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("effective_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_tax_rate",
                "abstract": False,
            },
        ),
    ]
