# Generated by Django 5.2.17 on 2026-08-17 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("projects", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="collected_account",
            field=models.ForeignKey(
                help_text="Output VAT — a liability.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="paid_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Input VAT — an asset when recoverable.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="accounting.taxrate",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "-created_at"], name="accounting__tenant__66cbec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "type", "is_active"], name="ix_account_type"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "is_reconcilable"], name="ix_account_reconcilable"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_account_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("system_key", ""), _negated=True),
                fields=("tenant", "system_key"),
                name="uq_account_system_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="ck_account_no_self_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsequence",
            index=models.Index(
                fields=["tenant", "-created_at"], name="accounting__tenant__e8a878_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "scope", "year"), name="uq_sequence_scope_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.CheckConstraint(
                condition=models.Q(("next_value__gte", 1)), name="ck_sequence_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(
                fields=["tenant", "-created_at"], name="accounting__tenant__7081d7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "from_currency", "to_currency", "rate_date"),
                name="uq_fx_rate_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gt", 0)), name="ck_fx_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_currency", models.F("to_currency")), _negated=True
                ),
                name="ck_fx_distinct_currencies",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalyear",
            index=models.Index(
                fields=["tenant", "-created_at"], name="accounting__tenant__054313_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalyear",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_fiscal_year_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalyear",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="ck_fiscal_year_date_order",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["tenant", "-created_at"], name="accounting__tenant__7b0179_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["tenant", "start_date", "end_date"], name="ix_period_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.UniqueConstraint(
                fields=("tenant", "start_date"), name="uq_period_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="ck_period_date_order",
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["tenant", "-created_at"], name="accounting__tenant__4ff720_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="journal",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_journal_code"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["tenant", "-created_at"], name="accounting__tenant__c48c6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["tenant", "status", "entry_date"], name="ix_entry_status"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["tenant", "period", "status"], name="ix_entry_period"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["source_document_type", "source_document_id"],
                name="ix_entry_source_doc",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("tenant", "journal", "number"),
                name="uq_entry_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_entry_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "posted"), _negated=True),
                    models.Q(
                        ("total_debit", models.F("total_credit")),
                        ("total_debit__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="ck_entry_balanced",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_debit__gte", 0), ("total_credit__gte", 0)),
                name="ck_entry_totals_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "posted"), _negated=True),
                    ("posted_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_entry_posted_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="ck_entry_fx_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="taxrate",
            index=models.Index(
                fields=["tenant", "-created_at"], name="accounting__tenant__5ce814_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code", "effective_from"), name="uq_tax_rate_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gte", 0), ("rate__lte", 1)),
                name="ck_tax_rate_fraction",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_tax_rate_period_order",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["tenant", "-created_at"], name="accounting__tenant__bcaea6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["tenant", "account"], name="ix_line_account"),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["tenant", "partner_type", "partner_id"], name="ix_line_partner"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["tenant", "project"], name="ix_line_project"),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["tenant", "department"], name="ix_line_department"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["account", "reconciled_at"], name="ix_line_unreconciled"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.UniqueConstraint(
                fields=("entry", "line_number"), name="uq_line_number_per_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit__gte", 0), ("credit__gte", 0)),
                name="ck_line_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("debit__gt", 0), ("credit", 0)),
                    models.Q(("credit__gt", 0), ("debit", 0)),
                    _connector="OR",
                ),
                name="ck_line_single_sided",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_debit__gte", 0), ("base_credit__gte", 0)),
                name="ck_line_base_non_negative",
            ),
        ),
    ]
