# Generated by Django 5.2.17 on 2026-08-22 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_ledger_guards'),
        ('tenancy', '0003_rls_nullable_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_code',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='income_category',
            field=models.CharField(choices=[('none', '—'), ('revenue', 'Revenue'), ('discount', 'Sales discounts'), ('returns', 'Sales returns'), ('cogs', 'Cost of goods sold'), ('operating', 'Operating expenses'), ('admin', 'General & administrative'), ('depreciation_tax', 'Depreciation & tax')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='normal_balance_override',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6),
        ),
        migrations.AddField(
            model_name='account',
            name='requires_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='segment_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('full_code__isnull', False)), fields=('tenant', 'full_code'), name='uq_account_full_code'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('segment_code__isnull', False)), fields=('tenant', 'parent', 'segment_code'), name='uq_account_parent_segment'),
        ),
    ]
