# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                "^[a-z0-9][a-z0-9-]*[a-z0-9]$"
                            ),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("suspended", "Suspended"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="trial",
                        max_length=16,
                    ),
                ),
                (
                    "country",
                    models.CharField(help_text="ISO-3166 alpha-2", max_length=2),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                (
                    "tax_registration_number",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tenancy_tenant",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["status"], name="ix_tenant_status")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fiscal_year_start_month__gte", 1),
                            ("fiscal_year_start_month__lte", 12),
                        ),
                        name="ck_tenant_fiscal_month_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("standard", "Standard"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("seats", models.PositiveIntegerField(default=1)),
                (
                    "monthly_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("started_on", models.DateField()),
                ("ended_on", models.DateField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_subscription",
                "ordering": ["-started_on"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_on__isnull", True),
                            ("ended_on__gte", models.F("started_on")),
                            _connector="OR",
                        ),
                        name="ck_subscription_period_order",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("ended_on__isnull", True)),
                        fields=("tenant",),
                        name="uq_subscription_one_open_per_tenant",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("actor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("login_failed", "Failed login"),
                            ("role_granted", "Role granted"),
                            ("role_revoked", "Role revoked"),
                            ("impersonation", "Platform admin impersonation"),
                            ("export", "Data export"),
                            ("period_closed", "Accounting period closed"),
                            ("entry_reversed", "Journal entry reversed"),
                            ("payroll_approved", "Payroll approved"),
                            ("setting_changed", "Setting changed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=64)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_audit_log",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-occurred_at"], name="ix_audit_tenant_time"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"], name="ix_audit_object"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_domain",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("tenant",),
                        name="uq_domain_one_primary_per_tenant",
                    )
                ],
            },
        ),
    ]
