# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.core.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("vendor_reference", models.CharField(blank=True, max_length=100)),
                ("bill_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(db_index=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("exchange_rate", apps.core.fields.RateField(default=1)),
                (
                    "subtotal_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "tax_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "withholding_amount",
                    apps.core.fields.MoneyField(
                        default=Decimal("0.000000"),
                        help_text="Tax withheld at source; reduces cash paid, not the expense.",
                    ),
                ),
                (
                    "total_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "amount_paid",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "amount_due",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("partially_paid", "Partially paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("voided", "Voided"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "expenses_bill",
                "ordering": ["-bill_date", "-number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveSmallIntegerField()),
                ("description", models.CharField(max_length=500)),
                ("quantity", apps.core.fields.QuantityField(default=1)),
                (
                    "unit_price",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "line_subtotal",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("line_tax", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "line_total",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("is_billable", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "expenses_bill_line",
                "ordering": ["bill", "line_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("exchange_rate", apps.core.fields.RateField(default=1)),
                ("amount", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "withholding_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "cash_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("company_card", "Company card"),
                            ("personal_card", "Personal card"),
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank transfer"),
                            ("petty_cash", "Petty cash"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "payment_batch_reference",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "expenses_bill_payment",
                "ordering": ["-payment_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("expense_date", models.DateField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("exchange_rate", apps.core.fields.RateField(default=1)),
                (
                    "amount",
                    apps.core.fields.MoneyField(
                        default=Decimal("0.000000"), help_text="Net of tax."
                    ),
                ),
                (
                    "tax_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "total_amount",
                    apps.core.fields.MoneyField(
                        default=Decimal("0.000000"),
                        help_text="Gross — what actually left the account.",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("company_card", "Company card"),
                            ("personal_card", "Personal card"),
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank transfer"),
                            ("petty_cash", "Petty cash"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("reimbursed", "Reimbursed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("is_billable", models.BooleanField(default=False)),
                ("is_reimbursable", models.BooleanField(default=False)),
                (
                    "markup_rate",
                    apps.core.fields.RateField(default=Decimal("0.000000")),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.CharField(blank=True, max_length=255)),
                ("reimbursed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "expenses_expense",
                "ordering": ["-expense_date", "-number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=150)),
                ("is_tax_deductible", models.BooleanField(default=True)),
                ("deductible_rate", apps.core.fields.RateField(default=1)),
                (
                    "approval_threshold_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("requires_receipt", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "expenses_category",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_key", models.CharField(max_length=500)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("ocr_text", models.TextField(blank=True)),
                (
                    "ocr_confidence",
                    apps.core.fields.RateField(blank=True, default=None, null=True),
                ),
                (
                    "ocr_extracted",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed merchant/date/total/tax.",
                    ),
                ),
                ("ocr_processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "expenses_receipt",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                ("address", models.JSONField(blank=True, default=dict)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("payment_terms_days", models.PositiveSmallIntegerField(default=30)),
                ("is_withholding_applicable", models.BooleanField(default=False)),
                (
                    "withholding_rate",
                    apps.core.fields.RateField(default=Decimal("0.000000")),
                ),
                ("bank_details", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "expenses_vendor",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
