# Generated by Django 5.2.17 on 2026-08-17 14:50

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0003_initial"),
        ("expenses", "0002_initial"),
        ("hr", "0002_initial"),
        ("inventory", "0001_initial"),
        ("projects", "0001_initial"),
        ("sales", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="expenses.bill",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_lines",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="expense_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_lines",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_lines",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_lines",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_lines",
                to="accounting.taxrate",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="expenses.bill",
            ),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_payment",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="paid_from_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_payments",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Claimant, for reimbursable staff spend.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="invoiced_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_expense",
                to="sales.invoiceline",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expense",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="paid_from_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses_paid",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="reimbursement_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reimbursed_expense",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="accounting.taxrate",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="default_tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expense_categories",
                to="accounting.taxrate",
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="expense_account",
            field=models.ForeignKey(
                help_text="Leaf expense account this category posts to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expense_categories",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="expenses.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="expenses.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_lines",
                to="expenses.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="expensereceipt",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expensereceipt",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="expenses.expense",
            ),
        ),
        migrations.AddField(
            model_name="expensereceipt",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="expensereceipt",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expensereceipt",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="default_expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_expense_vendors",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="payable_account",
            field=models.ForeignKey(
                help_text="AP control account this vendor's balance rolls up to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ap_vendors",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL when the merchant is not a tracked vendor.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="expenses.vendor",
            ),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_payments",
                to="expenses.vendor",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="expenses.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="expensecategory",
            index=models.Index(
                fields=["tenant", "-created_at"], name="expenses_ca_tenant__7bffa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expensecategory",
            index=models.Index(
                fields=["tenant", "is_active"], name="ix_expense_cat_active"
            ),
        ),
        migrations.AddIndex(
            model_name="expensecategory",
            index=models.Index(
                fields=["tenant", "parent"], name="ix_expense_cat_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_expense_category_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="ck_expense_category_no_self_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deductible_rate__gte", 0), ("deductible_rate__lte", 1)
                ),
                name="ck_expense_category_deductible_fraction",
            ),
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("approval_threshold_amount__gte", 0)),
                name="ck_expense_category_threshold_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="billline",
            index=models.Index(
                fields=["tenant", "-created_at"], name="expenses_bi_tenant__75489c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billline",
            index=models.Index(
                fields=["bill", "line_number"], name="ix_bill_line_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="billline",
            index=models.Index(
                fields=["tenant", "project"], name="ix_bill_line_project"
            ),
        ),
        migrations.AddIndex(
            model_name="billline",
            index=models.Index(
                fields=["tenant", "expense_account"], name="ix_bill_line_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="billline",
            constraint=models.UniqueConstraint(
                fields=("bill", "line_number"), name="uq_bill_line_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="billline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0), ("unit_price__gte", 0)),
                name="ck_bill_line_qty_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="billline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("line_subtotal__gte", 0),
                    ("line_tax__gte", 0),
                    ("line_total__gte", 0),
                ),
                name="ck_bill_line_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="billline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_billable", False), ("customer__isnull", False), _connector="OR"
                ),
                name="ck_bill_line_billable_has_customer",
            ),
        ),
        migrations.AddIndex(
            model_name="expensereceipt",
            index=models.Index(
                fields=["tenant", "-created_at"], name="expenses_re_tenant__261efd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expensereceipt",
            index=models.Index(fields=["expense"], name="ix_expense_receipt_parent"),
        ),
        migrations.AddIndex(
            model_name="expensereceipt",
            index=models.Index(
                fields=["tenant", "ocr_processed_at"], name="ix_expense_receipt_ocr"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensereceipt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sha256"), name="uq_expense_receipt_sha256"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensereceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gt", 0)),
                name="ck_expense_receipt_size_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="expensereceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ocr_confidence__isnull", True),
                    models.Q(("ocr_confidence__gte", 0), ("ocr_confidence__lte", 1)),
                    _connector="OR",
                ),
                name="ck_expense_receipt_confidence_fraction",
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["tenant", "-created_at"], name="expenses_ve_tenant__67c9bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["tenant", "is_active"], name="ix_vendor_active"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["tenant", "name"], name="ix_vendor_name"),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_vendor_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("withholding_rate__gte", 0), ("withholding_rate__lte", 1)
                ),
                name="ck_vendor_withholding_fraction",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["tenant", "-created_at"], name="expenses_ex_tenant__6562d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["tenant", "status", "expense_date"], name="ix_expense_status"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["tenant", "category"], name="ix_expense_category"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["tenant", "employee", "status"], name="ix_expense_employee"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["tenant", "project"], name="ix_expense_project"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["tenant", "vendor"], name="ix_expense_vendor"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                condition=models.Q(
                    ("invoiced_line__isnull", True), ("is_billable", True)
                ),
                fields=["tenant", "customer"],
                name="ix_expense_rebillable",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("tenant", "number"),
                name="uq_expense_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("amount"), "+", models.F("tax_amount")
                        ),
                    )
                ),
                name="ck_expense_total_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__gte", 0), ("tax_amount__gte", 0), ("total_amount__gt", 0)
                ),
                name="ck_expense_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="ck_expense_fx_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("markup_rate__gte", 0)),
                name="ck_expense_markup_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_billable", False), ("customer__isnull", False), _connector="OR"
                ),
                name="ck_expense_billable_has_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_reimbursable", False),
                    ("employee__isnull", False),
                    _connector="OR",
                ),
                name="ck_expense_reimbursable_has_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    ("approved_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_expense_approved_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "rejected"), _negated=True),
                    models.Q(("rejected_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_expense_rejected_has_reason",
            ),
        ),
        migrations.AddIndex(
            model_name="billpayment",
            index=models.Index(
                fields=["tenant", "-created_at"], name="expenses_bi_tenant__2ac8eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billpayment",
            index=models.Index(
                fields=["tenant", "status", "payment_date"], name="ix_bill_pmt_status"
            ),
        ),
        migrations.AddIndex(
            model_name="billpayment",
            index=models.Index(fields=["bill"], name="ix_bill_pmt_bill"),
        ),
        migrations.AddIndex(
            model_name="billpayment",
            index=models.Index(fields=["tenant", "vendor"], name="ix_bill_pmt_vendor"),
        ),
        migrations.AddConstraint(
            model_name="billpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("tenant", "number"),
                name="uq_bill_payment_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="billpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "cash_amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("amount"), "-", models.F("withholding_amount")
                        ),
                    )
                ),
                name="ck_bill_payment_cash_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="billpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__gt", 0),
                    ("withholding_amount__gte", 0),
                    ("cash_amount__gte", 0),
                ),
                name="ck_bill_payment_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="billpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("withholding_amount__lte", models.F("amount"))),
                name="ck_bill_payment_withholding_within_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="billpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="ck_bill_payment_fx_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["tenant", "-created_at"], name="expenses_bi_tenant__fc8ac7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["tenant", "status", "due_date"], name="ix_bill_status"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["tenant", "vendor", "status"], name="ix_bill_vendor"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["tenant", "bill_date"], name="ix_bill_date"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                condition=models.Q(("amount_due__gt", 0)),
                fields=["tenant", "due_date"],
                name="ix_bill_open_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("tenant", "number"),
                name="uq_bill_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vendor_reference", ""), _negated=True),
                fields=("tenant", "vendor", "vendor_reference"),
                name="uq_bill_vendor_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "amount_due",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total_amount"), "-", models.F("amount_paid")
                        ),
                    )
                ),
                name="ck_bill_due_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal_amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("withholding_amount__gte", 0),
                    ("total_amount__gte", 0),
                    ("amount_paid__gte", 0),
                ),
                name="ck_bill_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__lte", models.F("total_amount"))),
                name="ck_bill_no_overpayment",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_date__gte", models.F("bill_date"))),
                name="ck_bill_due_after_bill_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)), name="ck_bill_fx_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "voided"), _negated=True),
                    models.Q(("void_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_bill_void_has_reason",
            ),
        ),
    ]
