# Generated by Django 5.2.17 on 2026-08-19 19:02

import apps.core.fields
import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import rls_operations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_ledger_guards'),
        ('expenses', '0003_initial'),
        ('tenancy', '0003_rls_nullable_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBillProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('KWD', 'Kuwaiti Dinar')], max_length=3)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', max_length=12)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('next_run_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_occurrences', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occurrences_generated', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30)),
                ('auto_submit', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_profiles', to='expenses.vendor')),
            ],
            options={
                'db_table': 'expenses_recurring_bill_profile',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringBillLineTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', apps.core.fields.QuantityField(default=1)),
                ('unit_price', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.taxrate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expenses.recurringbillprofile')),
            ],
            options={
                'db_table': 'expenses_recurring_bill_line',
                'ordering': ['profile', 'line_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('KWD', 'Kuwaiti Dinar')], max_length=3)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-annual'), ('annual', 'Annual')], default='monthly', max_length=12)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('next_run_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_occurrences', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occurrences_generated', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('company_card', 'Company card'), ('personal_card', 'Personal card'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('petty_cash', 'Petty cash')], default='company_card', max_length=16)),
                ('amount', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('tax_amount', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_profiles', to='expenses.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_profiles', to='expenses.vendor')),
            ],
            options={
                'db_table': 'expenses_recurring_expense_profile',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('credit_date', models.DateField(db_index=True)),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('KWD', 'Kuwaiti Dinar')], max_length=3)),
                ('exchange_rate', apps.core.fields.RateField(default=1)),
                ('subtotal_amount', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('tax_amount', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('total_amount', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('amount_applied', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('amount_remaining', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('partially_applied', 'Partially applied'), ('applied', 'Applied'), ('voided', 'Voided')], db_index=True, default='draft', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_credits', to='expenses.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_credit', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='expenses.vendor')),
            ],
            options={
                'db_table': 'expenses_vendor_credit',
                'ordering': ['-credit_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorCreditLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', apps.core.fields.QuantityField(default=1)),
                ('unit_price', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('line_subtotal', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('line_tax', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('line_total', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expenses.vendorcredit')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.taxrate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses_vendor_credit_line',
                'ordering': ['credit_note', 'line_number'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='recurringbillprofile',
            index=models.Index(fields=['tenant', '-created_at'], name='expenses_re_tenant__f2a361_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringbillprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_recurring_bill_name'),
        ),
        migrations.AddConstraint(
            model_name='recurringbillprofile',
            constraint=models.CheckConstraint(condition=models.Q(('interval__gte', 1)), name='ck_recurring_bill_interval'),
        ),
        migrations.AddConstraint(
            model_name='recurringbillprofile',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='ck_recurring_bill_dates'),
        ),
        migrations.AddIndex(
            model_name='recurringbilllinetemplate',
            index=models.Index(fields=['tenant', '-created_at'], name='expenses_re_tenant__594463_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringbilllinetemplate',
            constraint=models.UniqueConstraint(fields=('profile', 'line_number'), name='uq_recurring_bill_line_number'),
        ),
        migrations.AddIndex(
            model_name='recurringexpenseprofile',
            index=models.Index(fields=['tenant', '-created_at'], name='expenses_re_tenant__774ced_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpenseprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_recurring_expense_name'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpenseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('interval__gte', 1)), name='ck_recurring_expense_interval'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpenseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_recurring_expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpenseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='ck_recurring_expense_dates'),
        ),
        migrations.AddIndex(
            model_name='vendorcredit',
            index=models.Index(fields=['tenant', 'vendor', '-credit_date'], name='ix_vcredit_vendor'),
        ),
        migrations.AddIndex(
            model_name='vendorcredit',
            index=models.Index(fields=['tenant', 'status'], name='ix_vcredit_status'),
        ),
        migrations.AddConstraint(
            model_name='vendorcredit',
            constraint=models.CheckConstraint(condition=models.Q(('amount_remaining', django.db.models.expressions.CombinedExpression(models.F('total_amount'), '-', models.F('amount_applied')))), name='ck_vendor_credit_remaining_identity'),
        ),
        migrations.AddConstraint(
            model_name='vendorcredit',
            constraint=models.CheckConstraint(condition=models.Q(('amount_applied__lte', models.F('total_amount'))), name='ck_vendor_credit_no_overapplication'),
        ),
        migrations.AddConstraint(
            model_name='vendorcredit',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0), ('amount_applied__gte', 0)), name='ck_vendor_credit_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vendorcredit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'voided'), _negated=True), models.Q(('void_reason', ''), _negated=True), _connector='OR'), name='ck_vendor_credit_void_has_reason'),
        ),
        migrations.AddIndex(
            model_name='vendorcreditline',
            index=models.Index(fields=['tenant', '-created_at'], name='expenses_ve_tenant__554a9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorcreditline',
            constraint=models.UniqueConstraint(fields=('credit_note', 'line_number'), name='uq_vendor_credit_line_number'),
        ),
        migrations.AddConstraint(
            model_name='vendorcreditline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('unit_price__gte', 0)), name='ck_vendor_credit_line_non_negative'),
        ),
            *rls_operations(
            "expenses_vendor_credit",
            "expenses_vendor_credit_line",
            "expenses_recurring_bill_profile",
            "expenses_recurring_bill_line",
            "expenses_recurring_expense_profile",
        ),
    ]
