# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.core.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("hr", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=150)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("deduction", "Employee deduction"),
                            ("employer_contribution", "Employer contribution"),
                            ("informational", "Informational only"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed amount"),
                            ("percentage_of_base", "Percentage of base salary"),
                            ("percentage_of_gross", "Percentage of gross"),
                            ("formula", "Restricted formula"),
                            ("per_unit", "Rate per unit (overtime hours, pieces)"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                ("amount", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                ("rate", apps.core.fields.RateField(default=Decimal("0.000000"))),
                ("formula_expression", models.CharField(blank=True, max_length=500)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_subject_to_social_insurance", models.BooleanField(default=True)),
                ("affects_net", models.BooleanField(default=True)),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        default=500,
                        help_text="Evaluation order; see the class docstring.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_expense_components",
                        to="accounting.account",
                    ),
                ),
                (
                    "liability_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_liability_components",
                        to="accounting.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_component",
                "ordering": ["sequence", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_override",
                    apps.core.fields.MoneyField(blank=True, default=None, null=True),
                ),
                (
                    "rate_override",
                    apps.core.fields.RateField(blank=True, default=None, null=True),
                ),
                (
                    "quantity",
                    apps.core.fields.QuantityField(
                        default=Decimal("0.000000"),
                        help_text="Units for PER_UNIT components.",
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_components",
                        to="hr.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="payroll.payrollcomponent",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_employee_component",
                "ordering": ["employee", "component"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("pay_date", models.DateField(db_index=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("biweekly", "Bi-weekly"),
                            ("weekly", "Weekly"),
                            ("off_cycle", "Off-cycle"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("calculating", "Calculating"),
                            ("calculated", "Calculated"),
                            ("pending_approval", "Pending approval"),
                            ("approved", "Approved"),
                            ("posted", "Posted to ledger"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(default=0)),
                (
                    "total_gross",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "total_deductions",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "total_employer_cost",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("total_net", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Freezes payslip edits while the run is under review.",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs",
                        to="hr.department",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_run",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_run",
                "ordering": ["-period_start"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayrollBankFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("file_format", models.CharField(default="csv", max_length=30)),
                ("file_key", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent to bank"),
                            ("confirmed", "Confirmed by bank"),
                            ("rejected", "Rejected by bank"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "total_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("employee_count", models.PositiveIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("value_date", models.DateField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("bank_response", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_bank_files",
                        to="accounting.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_files",
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_bank_file",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "working_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "paid_days",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "leave_days_unpaid",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "overtime_hours",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                (
                    "gross_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "taxable_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "income_tax_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "social_insurance_employee",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "social_insurance_employer",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "other_deductions",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "net_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("in_bank_file", "In bank file"),
                            ("paid", "Paid"),
                            ("failed", "Payment failed"),
                            ("held", "Held"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=14,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_key", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="hr.employee",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="payroll.payrollrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_payslip",
                "ordering": ["run", "employee"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayslipLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("component_snapshot", models.JSONField(blank=True, default=dict)),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "quantity",
                    apps.core.fields.QuantityField(default=Decimal("0.000000")),
                ),
                ("rate", apps.core.fields.RateField(default=Decimal("0.000000"))),
                ("amount", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                ("is_taxable", models.BooleanField(default=True)),
                ("calculation_note", models.CharField(blank=True, max_length=255)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslip_lines",
                        to="payroll.payrollcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payroll.payslip",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_payslip_line",
                "ordering": ["payslip", "sequence"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryDisbursement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("beneficiary_iban", models.CharField(blank=True, max_length=64)),
                ("beneficiary_bank", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("settled", "Settled"),
                            ("failed", "Failed"),
                            ("returned", "Returned by bank"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                (
                    "bank_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="payroll.payrollbankfile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements",
                        to="hr.employee",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements",
                        to="payroll.payslip",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_salary_disbursement",
                "ordering": ["bank_file", "employee"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxBracket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.CharField(help_text="ISO-3166 alpha-2.", max_length=2),
                ),
                ("effective_from", models.DateField(db_index=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "lower_bound",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "upper_bound",
                    apps.core.fields.MoneyField(blank=True, default=None, null=True),
                ),
                (
                    "rate",
                    apps.core.fields.RateField(
                        default=Decimal("0.000000"),
                        help_text="Fraction, e.g. 0.225000 for 22.5%.",
                    ),
                ),
                (
                    "fixed_deduction",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("is_annual_basis", models.BooleanField(default=True)),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_tax_bracket",
                "ordering": ["country", "-effective_from", "sequence", "lower_bound"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeePayrollProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pay_frequency", models.CharField(blank=True, max_length=10)),
                ("is_exempt_from_tax", models.BooleanField(default=False)),
                ("is_exempt_from_social_insurance", models.BooleanField(default=False)),
                (
                    "tax_exemption_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("dependants_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "insurable_wage",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "payment_method",
                    models.CharField(default="bank_transfer", max_length=20),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        default="EGP",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_profile",
                        to="hr.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_employee_profile",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="payroll_emp_tenant__1370ce_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_active"], name="ix_pay_profile_active"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "employee"), name="uq_pay_profile_employee"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tax_exemption_amount__gte", 0), ("insurable_wage__gte", 0)
                        ),
                        name="ck_pay_profile_non_negative",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payrollcomponent",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payroll_com_tenant__19e00a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollcomponent",
            index=models.Index(
                fields=["tenant", "is_active", "sequence"],
                name="ix_pay_comp_eval_order",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollcomponent",
            index=models.Index(
                fields=["tenant", "component_type"], name="ix_pay_comp_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcomponent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_pay_component_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0), ("rate__gte", 0)),
                name="ck_pay_component_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__lte", 1)),
                name="ck_pay_component_rate_fraction",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("calculation_type", "formula"), _negated=True),
                    models.Q(("formula_expression", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_pay_component_formula_present",
            ),
        ),
        migrations.AddIndex(
            model_name="employeecomponent",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payroll_emp_tenant__083bca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeecomponent",
            index=models.Index(
                fields=["tenant", "employee", "effective_from"],
                name="ix_pay_empcomp_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeecomponent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "employee", "component", "effective_from"),
                name="uq_pay_emp_component_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeecomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="ck_pay_emp_component_date_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeecomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_override__isnull", True),
                    ("amount_override__gte", 0),
                    _connector="OR",
                ),
                name="ck_pay_emp_component_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payroll_run_tenant__11125c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(fields=["tenant", "status"], name="ix_pay_run_status"),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["tenant", "period_start", "period_end"],
                name="ix_pay_run_period",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["tenant", "pay_date"], name="ix_pay_run_pay_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("tenant", "period_start", "period_end", "frequency"),
                name="uq_pay_run_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="ck_pay_run_period_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_gross__gte", 0),
                    ("total_deductions__gte", 0),
                    ("total_net__gte", 0),
                    ("total_employer_cost__gte", 0),
                ),
                name="ck_pay_run_totals_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["posted", "paid"]), _negated=True),
                    ("journal_entry__isnull", False),
                    _connector="OR",
                ),
                name="ck_pay_run_posted_has_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    ("approved_by__isnull", False),
                    _connector="OR",
                ),
                name="ck_pay_run_approved_has_approver",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollbankfile",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payroll_ban_tenant__9810fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollbankfile",
            index=models.Index(fields=["tenant", "run"], name="ix_pay_bankfile_run"),
        ),
        migrations.AddIndex(
            model_name="payrollbankfile",
            index=models.Index(
                fields=["tenant", "status"], name="ix_pay_bankfile_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollbankfile",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="ck_pay_bank_file_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollbankfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                fields=("tenant", "reference"),
                name="uq_pay_bank_file_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payroll_pay_tenant__7c8627_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(fields=["tenant", "run"], name="ix_pay_slip_run"),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["tenant", "employee"], name="ix_pay_slip_employee"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["tenant", "payment_status"], name="ix_pay_slip_payment"
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.UniqueConstraint(
                fields=("tenant", "run", "employee"), name="uq_pay_payslip_run_employee"
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.CheckConstraint(
                condition=models.Q(("gross_amount__gte", 0), ("net_amount__gte", 0)),
                name="ck_pay_payslip_gross_net_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("income_tax_amount__gte", 0),
                    ("social_insurance_employee__gte", 0),
                    ("social_insurance_employer__gte", 0),
                    ("other_deductions__gte", 0),
                    ("taxable_amount__gte", 0),
                ),
                name="ck_pay_payslip_components_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.CheckConstraint(
                condition=models.Q(("net_amount__lte", models.F("gross_amount"))),
                name="ck_pay_payslip_net_lte_gross",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("paid_days__gte", 0),
                    ("working_days__gte", 0),
                    ("overtime_hours__gte", 0),
                ),
                name="ck_pay_payslip_days_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="payslipline",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payroll_pay_tenant__42712b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslipline",
            index=models.Index(
                fields=["tenant", "payslip"], name="ix_pay_slip_line_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="payslipline",
            index=models.Index(
                fields=["tenant", "component"], name="ix_pay_slip_line_comp"
            ),
        ),
        migrations.AddConstraint(
            model_name="payslipline",
            constraint=models.UniqueConstraint(
                fields=("payslip", "sequence"), name="uq_pay_slip_line_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="payslipline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="ck_pay_slip_line_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="salarydisbursement",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payroll_sal_tenant__16937f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salarydisbursement",
            index=models.Index(fields=["tenant", "bank_file"], name="ix_pay_disb_file"),
        ),
        migrations.AddIndex(
            model_name="salarydisbursement",
            index=models.Index(
                fields=["tenant", "employee"], name="ix_pay_disb_employee"
            ),
        ),
        migrations.AddIndex(
            model_name="salarydisbursement",
            index=models.Index(fields=["tenant", "status"], name="ix_pay_disb_status"),
        ),
        migrations.AddConstraint(
            model_name="salarydisbursement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "bank_file", "payslip"),
                name="uq_pay_disbursement_slip",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarydisbursement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="ck_pay_disbursement_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarydisbursement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "failed"), _negated=True),
                    models.Q(("failure_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_pay_disbursement_failure_reason",
            ),
        ),
        migrations.AddIndex(
            model_name="taxbracket",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payroll_tax_tenant__d67d9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxbracket",
            index=models.Index(
                fields=["tenant", "country", "effective_from"],
                name="ix_pay_bracket_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxbracket",
            constraint=models.UniqueConstraint(
                fields=("tenant", "country", "effective_from", "lower_bound"),
                name="uq_pay_tax_bracket_slab",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxbracket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("upper_bound__isnull", True),
                    ("upper_bound__gt", models.F("lower_bound")),
                    _connector="OR",
                ),
                name="ck_pay_tax_bracket_bound_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxbracket",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gte", 0), ("rate__lte", 1)),
                name="ck_pay_tax_bracket_rate_fraction",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxbracket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lower_bound__gte", 0), ("fixed_deduction__gte", 0)
                ),
                name="ck_pay_tax_bracket_non_negative",
            ),
        ),
    ]
