# Generated by Django 5.2.17 on 2026-08-19 14:14

import apps.core.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import rls_operations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_overtime_and_salary_structures'),
        ('payroll', '0001_initial'),
        ('tenancy', '0003_rls_nullable_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('KWD', 'Kuwaiti Dinar')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_salary_structure',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField(db_index=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('base_salary', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('KWD', 'Kuwaiti Dinar')], max_length=3)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_structures', to='hr.employee')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='payroll.salarystructure')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_salary_structure_assignment',
                'ordering': ['-from_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', apps.core.fields.MoneyField(default=Decimal('0.000000'))),
                ('percentage_of_base', apps.core.fields.RateField(default=0)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_lines', to='payroll.payrollcomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.salarystructure')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_salary_structure_line',
                'ordering': ['structure', 'sequence', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['tenant', '-created_at'], name='payroll_sal_tenant__013de0_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_payroll_structure_code'),
        ),
        migrations.AddIndex(
            model_name='salarystructureassignment',
            index=models.Index(fields=['tenant', 'employee', '-from_date'], name='ix_payroll_asg_emp'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'from_date'), name='uq_payroll_assignment_start'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureassignment',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__isnull', True), ('to_date__gte', models.F('from_date')), _connector='OR'), name='ck_payroll_assignment_dates'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureassignment',
            constraint=models.CheckConstraint(condition=models.Q(('base_salary__gt', 0)), name='ck_payroll_assignment_base_positive'),
        ),
        migrations.AddIndex(
            model_name='salarystructureline',
            index=models.Index(fields=['tenant', '-created_at'], name='payroll_sal_tenant__f91093_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureline',
            constraint=models.UniqueConstraint(fields=('structure', 'component'), name='uq_payroll_structure_component'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('percentage_of_base__gte', 0)), name='ck_payroll_structure_line_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('percentage_of_base', 0)), models.Q(('amount', 0), ('percentage_of_base__gt', 0)), _connector='OR'), name='ck_payroll_structure_line_one_sizing'),
        ),
            *rls_operations("payroll_salary_structure", "payroll_salary_structure_line", "payroll_salary_structure_assignment"),
    ]
