# Generated by Django 5.2.17 on 2026-08-17 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0002_initial"),
        ("iam", "0001_initial"),
        ("projects", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roleassignment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="iam.role",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="iam.permission",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="iam.role",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles", through="iam.RolePermission", to="iam.permission"
            ),
        ),
        migrations.AddField(
            model_name="scoperule",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scope_rules",
                to="iam.role",
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="iam.tenantmembership",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="ix_user_active"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["tenant", "revoked_at"], name="ix_apikey_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="uq_role_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_role_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("code",),
                name="uq_role_system_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_system", True), ("tenant__isnull", True)),
                    models.Q(("is_system", False), ("tenant__isnull", False)),
                    _connector="OR",
                ),
                name="ck_role_system_has_no_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="scoperule",
            constraint=models.UniqueConstraint(
                fields=("role", "resource"), name="uq_scope_rule_role_resource"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(
                fields=["user", "is_active"], name="ix_membership_user_active"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(
                fields=["tenant", "is_active"], name="ix_membership_tenant_act"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmembership",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user"), name="uq_membership_tenant_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee__isnull", False)),
                fields=("tenant", "employee"),
                name="uq_membership_tenant_employee",
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(
                fields=["membership", "valid_until"], name="ix_assign_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                fields=("membership", "role", "department", "project"),
                name="uq_assignment_unique_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="ck_assignment_validity_order",
            ),
        ),
    ]
