# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.core.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                ("applied_on", models.DateField(db_index=True)),
                (
                    "exchange_rate_used",
                    apps.core.fields.RateField(
                        default=1,
                        help_text="Payment currency -> invoice currency at application time.",
                    ),
                ),
                (
                    "fx_gain_loss_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("is_reversed", models.BooleanField(default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "payments_payment_application",
                "ordering": ["-applied_on"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("braintree", "Braintree"),
                            ("authorize_net", "Authorize.Net"),
                            ("manual", "Manual / offline"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Shown on the checkout page and in reports.",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_test_mode", models.BooleanField(default=False)),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ENCRYPTED AT REST — see the class docstring before reading.",
                    ),
                ),
                ("webhook_secret_ref", models.CharField(blank=True, max_length=255)),
                ("webhook_endpoint_id", models.CharField(blank=True, max_length=255)),
                (
                    "supported_currencies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("EGP", "Egyptian Pound"),
                                ("USD", "US Dollar"),
                                ("EUR", "Euro"),
                                ("GBP", "Pound Sterling"),
                                ("SAR", "Saudi Riyal"),
                                ("AED", "UAE Dirham"),
                                ("KWD", "Kuwaiti Dinar"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "payments_gateway_config",
                "ordering": ["provider", "display_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("refund_date", models.DateField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("gateway_refund_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "fee_refunded_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("failure_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "payments_refund",
                "ordering": ["-refund_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_event_id", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. payment_intent.succeeded",
                        max_length=100,
                    ),
                ),
                ("raw_payload", models.JSONField()),
                ("signature_verified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "payments_webhook_event",
                "ordering": ["-received_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    apps.core.fields.MoneyField(
                        default=Decimal("0.000000"),
                        help_text="Gross amount received from the customer.",
                    ),
                ),
                (
                    "unapplied_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "fee_amount",
                    apps.core.fields.MoneyField(
                        default=Decimal("0.000000"),
                        help_text="Processor fee, expensed gross.",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("wallet", "Digital wallet"),
                            ("gateway", "Gateway (other)"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("settled", "Settled"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                            ("disputed", "Disputed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Cheque number, wire reference.",
                        max_length=100,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("failure_message", models.TextField(blank=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
                "ordering": ["-payment_date", "-number"],
                "abstract": False,
            },
        ),
    ]
