# Generated by Django 5.2.17 on 2026-08-17 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0003_initial"),
        ("payments", "0001_initial"),
        ("sales", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="deposit_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposited_payments",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentapplication",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentapplication",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_applications",
                to="sales.invoice",
            ),
        ),
        migrations.AddField(
            model_name="paymentapplication",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentapplication",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="paymentapplication",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentgatewayconfig",
            name="clearing_account",
            field=models.ForeignKey(
                help_text="Undeposited funds / gateway clearing (an asset).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gateway_clearing_configs",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="paymentgatewayconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentgatewayconfig",
            name="fee_account",
            field=models.ForeignKey(
                help_text="Processing fee expense.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gateway_fee_configs",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="paymentgatewayconfig",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="paymentgatewayconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL for offline receipts.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.paymentgatewayconfig",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="gateway",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="webhook_events",
                to="payments.paymentgatewayconfig",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="webhook_events",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="refund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="webhook_events",
                to="payments.refund",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="paymentapplication",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payments_pa_tenant__838373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentapplication",
            index=models.Index(fields=["invoice"], name="ix_payment_app_invoice"),
        ),
        migrations.AddIndex(
            model_name="paymentapplication",
            index=models.Index(fields=["payment"], name="ix_payment_app_payment"),
        ),
        migrations.AddIndex(
            model_name="paymentapplication",
            index=models.Index(
                fields=["tenant", "applied_on"], name="ix_payment_app_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentapplication",
            constraint=models.UniqueConstraint(
                fields=("payment", "invoice"), name="uq_payment_application_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ck_payment_application_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate_used__gt", 0)),
                name="ck_payment_application_fx_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_reversed", False),
                    ("reversed_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_payment_application_reversal_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgatewayconfig",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payments_ga_tenant__749a05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgatewayconfig",
            index=models.Index(
                fields=["tenant", "provider", "is_active"], name="ix_gateway_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentgatewayconfig",
            constraint=models.UniqueConstraint(
                fields=("tenant", "provider", "display_name"),
                name="uq_gateway_config_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentgatewayconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("tenant",),
                name="uq_gateway_config_single_default",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payments_pa_tenant__849b1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "status", "payment_date"], name="ix_payment_status"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "customer"], name="ix_payment_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["tenant", "method"], name="ix_payment_method"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["tenant", "gateway"], name="ix_payment_gateway"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway_transaction_id"], name="ix_payment_gateway_txn_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                condition=models.Q(("unapplied_amount__gt", 0)),
                fields=["tenant", "customer"],
                name="ix_payment_unapplied",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("tenant", "number"),
                name="uq_payment_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_payment_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_transaction_id", ""), _negated=True),
                fields=("gateway", "gateway_transaction_id"),
                name="uq_payment_gateway_txn",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gateway__isnull", True),
                    models.Q(("idempotency_key", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_payment_gateway_has_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__gt", 0),
                    ("fee_amount__gte", 0),
                    ("unapplied_amount__gte", 0),
                ),
                name="ck_payment_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("unapplied_amount__lte", models.F("amount"))),
                name="ck_payment_unapplied_within_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "captured"), _negated=True),
                    ("captured_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_payment_captured_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "failed"), _negated=True),
                    models.Q(("failure_code", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_payment_failed_has_code",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payments_re_tenant__462b8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["tenant", "status", "refund_date"], name="ix_refund_status"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["payment"], name="ix_refund_payment"),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("tenant", "number"),
                name="uq_refund_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_refund_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_refund_id", ""), _negated=True),
                fields=("tenant", "gateway_refund_id"),
                name="uq_refund_gateway_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0), ("fee_refunded_amount__gte", 0)),
                name="ck_refund_amounts_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["tenant", "-created_at"], name="payments_we_tenant__417f88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["tenant", "status", "received_at"], name="ix_webhook_status"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["tenant", "event_type"], name="ix_webhook_event_type"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["gateway", "provider_event_id"], name="ix_webhook_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                condition=models.Q(
                    ("status__in", ["received", "processing", "failed"])
                ),
                fields=["received_at"],
                name="ix_webhook_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "gateway", "provider_event_id"),
                name="uq_webhook_event_provider_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "processed"), _negated=True),
                    ("processed_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_webhook_processed_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "processed"), _negated=True),
                    ("signature_verified", True),
                    _connector="OR",
                ),
                name="ck_webhook_processed_was_verified",
            ),
        ),
    ]
