"""
Accounts-receivable endpoints.

Every move an invoice makes is a POST to a sub-resource that runs
``apps.sales.services.invoice_workflow``. None of it is reachable by writing a
field, and that is the point: issuing an invoice allocates a gapless number,
posts a balanced journal entry and releases stock, in one transaction. A
``PATCH {"status": "sent"}`` would do none of those three and would return 200,
leaving the ledger and the document permanently disagreeing.

The transitions here are generated by
:func:`apps.core.viewsets.transition_action` because the workflow services
already have the shape it expects — ``(invoice_id, *, tenant_id, user_id,
...)``. That buys idempotency-key handling, the savepoint, the service-error
translation and the refreshed response body without any of it being rewritten
per action.
"""

from __future__ import annotations

import logging
from typing import Any, Optional

from django.db.models import Q, Sum
from django.utils import timezone
from rest_framework import serializers, status
from rest_framework.decorators import action
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.response import Response

from apps.accounting.viewsets import IdempotentActionMixin, NotImplementedYet
from apps.core.exceptions import DomainError
from apps.core.fields import ZERO
from apps.core.pagination import SmallPagePagination
from apps.core.serializers import (
    ReasonRequiredTransitionSerializer,
    TransitionSerializer,
)
from apps.core.viewsets import TenantModelViewSet, transition_action
from apps.sales.models import (
    CreditNote,
    Customer,
    Invoice,
    InvoiceAttachment,
    PaymentReminderLog,
    PaymentReminderRule,
    RecurringInvoiceProfile,
)
from apps.sales.serializers import (
    CreditNoteSerializer,
    CustomerSerializer,
    InvoiceAttachmentSerializer,
    InvoiceAttachmentUploadSerializer,
    InvoiceSerializer,
    PaymentReminderRuleSerializer,
    RecurringInvoiceProfileSerializer,
)

logger = logging.getLogger(__name__)

#: Invoice states that still contribute to the AR control account.
OPEN_INVOICE_STATUSES = (
    Invoice.Status.SENT,
    Invoice.Status.PARTIALLY_PAID,
    Invoice.Status.OVERDUE,
)


class WriteOffInputSerializer(ReasonRequiredTransitionSerializer):
    """Body for ``POST /invoices/{id}/write-off``.

    ``write_off_date`` is separate from the invoice's own dates because a bad
    debt is recognised when it is *decided*, not when the invoice was raised.
    Defaulting it to today (in the service) rather than to the invoice date
    keeps the expense in the period the decision was taken, which is where an
    auditor expects to find it.
    """

    write_off_date = serializers.DateField(required=False, allow_null=True)


class SendReminderInputSerializer(TransitionSerializer):
    """Body for ``POST /invoices/{id}/send-reminder``."""

    rule = serializers.UUIDField(
        required=False,
        allow_null=True,
        help_text="PaymentReminderRule to use. Defaults to the oldest active rule.",
    )


# ---------------------------------------------------------------------------
# Customers
# ---------------------------------------------------------------------------

class CustomerViewSet(TenantModelViewSet):
    """Customer master data, statements and per-customer invoice lists."""

    permission_domain = "sales"
    resource = "customer"
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer
    select_related = ("receivable_account",)
    pagination_class = SmallPagePagination
    filterset_fields = ("is_active", "currency", "has_credit_limit")
    search_fields = ("code", "name", "display_name", "email", "tax_number")
    ordering_fields = ("name", "code", "created_at")
    ordering = ("name",)
    extra_permissions = {
        "statement": ["sales.customer.read", "sales.invoice.read"],
        "invoices": ["sales.invoice.read"],
        "archive": ["sales.customer.archive"],
    }

    def get_queryset(self):
        """Annotate the open balance so a list page is one query, not N+1.

        Filtered aggregate rather than a subquery per row: a page of 100
        customers each triggering its own ``SUM(amount_due)`` is 100 round
        trips, and it is the AR list that the credit controller reloads all
        day.
        """
        return super().get_queryset().annotate(
            outstanding_balance=Sum(
                "invoices__amount_due",
                filter=Q(invoices__status__in=OPEN_INVOICE_STATUSES),
            )
        )

    @action(detail=True, methods=["get"], url_path="statement")
    def statement(self, request, pk=None):
        """Everything this customer owes, and what it is made up of.

        The document a credit controller sends when a customer says "what is
        this balance?". Deliberately built from the invoices and credit notes
        themselves rather than from the AR control account: the control account
        knows the total, only the sub-ledger knows which documents make it up,
        and a statement that cannot be broken down is one nobody can dispute or
        agree.

        Unpaginated and bounded by a date window (default: the last 12 months)
        for the same reason the tree endpoint is unpaginated — a statement cut
        in half at an arbitrary row is not a statement.
        """
        from django.utils.dateparse import parse_date

        customer = self.get_object()
        raw_from = request.query_params.get("date_from")
        raw_to = request.query_params.get("date_to")
        date_to = parse_date(raw_to) if raw_to else timezone.localdate()
        date_from = (
            parse_date(raw_from)
            if raw_from
            else date_to.replace(year=date_to.year - 1)
        )

        invoices = (
            Invoice.objects.filter(
                customer=customer, issue_date__gte=date_from, issue_date__lte=date_to
            )
            .exclude(status=Invoice.Status.DRAFT)
            .order_by("issue_date", "number")
        )
        credit_notes = (
            CreditNote.objects.filter(
                customer=customer, issue_date__gte=date_from, issue_date__lte=date_to
            )
            .exclude(status=CreditNote.Status.DRAFT)
            .order_by("issue_date", "number")
        )

        rows: list[dict[str, Any]] = []
        for invoice in invoices:
            rows.append(
                {
                    "type": "invoice",
                    "id": str(invoice.id),
                    "number": invoice.number,
                    "date": invoice.issue_date.isoformat(),
                    "due_date": invoice.due_date.isoformat(),
                    "currency": invoice.currency,
                    "status": invoice.status,
                    "total_amount": f"{invoice.total_amount:f}",
                    "amount_paid": f"{invoice.amount_paid:f}",
                    "amount_due": f"{invoice.amount_due:f}",
                }
            )
        for note in credit_notes:
            rows.append(
                {
                    "type": "credit_note",
                    "id": str(note.id),
                    "number": note.number,
                    "date": note.issue_date.isoformat(),
                    "currency": note.currency,
                    "status": note.status,
                    "total_amount": f"{-note.total_amount:f}",
                    "amount_remaining": f"{note.amount_remaining:f}",
                }
            )
        rows.sort(key=lambda row: (row["date"], row.get("number") or ""))

        outstanding = Invoice.objects.filter(
            customer=customer, status__in=OPEN_INVOICE_STATUSES
        ).aggregate(total=Sum("amount_due"))["total"] or ZERO
        unapplied_credit = CreditNote.objects.filter(
            customer=customer, status__in=[CreditNote.Status.ISSUED]
        ).aggregate(total=Sum("amount_remaining"))["total"] or ZERO

        return Response(
            {
                "customer": {
                    "id": str(customer.id),
                    "code": customer.code,
                    "name": customer.name,
                    "currency": customer.currency,
                },
                "period": {"from": date_from.isoformat(), "to": date_to.isoformat()},
                "lines": rows,
                "outstanding_balance": f"{outstanding:f}",
                "unapplied_credit": f"{unapplied_credit:f}",
                "net_balance": f"{outstanding - unapplied_credit:f}",
                "as_of": timezone.now().isoformat(),
            }
        )

    @action(detail=True, methods=["get"], url_path="invoices")
    def invoices(self, request, pk=None):
        """This customer's invoices, paginated with the standard cursor.

        A filtered ``/invoices/?customer=<id>`` would serve the same rows, but
        the nested route is what the customer detail screen calls and it keeps
        the ABAC scope of *both* resources in play: the customer must be
        visible to the caller, and the invoices are then narrowed again by the
        invoice scope.
        """
        customer = self.get_object()
        queryset = (
            Invoice.objects.filter(customer=customer)
            .select_related("customer", "journal_entry")
            .order_by("-issue_date", "-number")
        )
        status_filter = request.query_params.getlist("status")
        if status_filter:
            queryset = queryset.filter(status__in=status_filter)
        if request.query_params.get("open_only") == "true":
            queryset = queryset.filter(status__in=OPEN_INVOICE_STATUSES)

        page = self.paginate_queryset(queryset)
        context = self.get_serializer_context()
        if page is not None:
            return self.get_paginated_response(
                InvoiceSerializer(page, many=True, context=context).data
            )
        return Response(InvoiceSerializer(queryset, many=True, context=context).data)


# ---------------------------------------------------------------------------
# Invoices
# ---------------------------------------------------------------------------

class InvoiceViewSet(IdempotentActionMixin, TenantModelViewSet):
    """Customer invoices and the five moves they can make.

    Lines are editable only while the invoice is DRAFT — enforced on
    :class:`~apps.sales.serializers.InvoiceSerializer`, which turns the nested
    ``lines`` field read-only once the status leaves DRAFT. After issue the
    document has been sent to a customer and posted to the ledger; the
    corrections are a credit note (reduce what is owed) or a write-off
    (recognise it will not be collected), never an edit.
    """

    permission_domain = "sales"
    resource = "invoice"
    queryset = Invoice.objects.all()
    serializer_class = InvoiceSerializer
    select_related = ("customer", "journal_entry", "project")
    prefetch_related = ("lines", "lines__tax_rate")
    filterset_fields = (
        "status", "customer", "currency", "project", "issue_date", "due_date",
    )
    search_fields = ("number", "order_number", "subject", "customer__name", "customer__code", "notes")
    ordering_fields = ("issue_date", "due_date", "number", "total_amount", "amount_due")
    ordering = ("-issue_date", "-number")
    extra_permissions = {
        "attachments": ["sales.invoice.update"],
        "issue": ["sales.invoice.issue"],
        "void": ["sales.invoice.void"],
        "write_off": ["sales.invoice.write_off"],
        "send_reminder": ["sales.invoice.send"],
        "pdf": ["sales.invoice.read"],
        "journal_entry": ["sales.invoice.read", "accounting.journal_entry.read"],
    }

    @action(detail=True, methods=["get", "post"], url_path="attachments",
            parser_classes=[MultiPartParser, FormParser])
    def attachments(self, request, pk=None):
        """``GET`` lists this invoice's files; ``POST`` uploads one.

        Multipart, one file per request. Not a JSON body with base64: a 10 MB
        PDF becomes 13 MB of base64 that has to be held in memory as a string
        on both sides, and every proxy in between logs the request body.

        The hash is computed by streaming the upload in chunks rather than
        calling ``.read()`` — Django spools anything over
        ``FILE_UPLOAD_MAX_MEMORY_SIZE`` to a temp file precisely so it never
        has to be resident, and reading it whole gives that back.

        Allowed while the invoice is issued, unlike editing it. An attachment
        does not change what the invoice *says* — the signed delivery note
        usually arrives after the invoice has gone out, and refusing it would
        mean the evidence lives in somebody's inbox instead.
        """
        import hashlib  # noqa: PLC0415

        invoice = self.get_object()

        if request.method == "GET":
            rows = InvoiceAttachment.objects.filter(invoice=invoice)
            return Response(
                InvoiceAttachmentSerializer(
                    rows, many=True, context=self.get_serializer_context()
                ).data
            )

        body = InvoiceAttachmentUploadSerializer(data=request.data)
        body.is_valid(raise_exception=True)
        upload = body.validated_data["file"]

        digest = hashlib.sha256()
        for chunk in upload.chunks():
            digest.update(chunk)
        sha256 = digest.hexdigest()
        upload.seek(0)

        # Checked here for a readable message; `uq_invoice_attachment_sha256`
        # is what actually guarantees it against two concurrent uploads.
        if InvoiceAttachment.objects.filter(
            invoice=invoice, sha256=sha256
        ).exists():
            raise DomainError(
                f"{upload.name} is already attached to this invoice. "
                f"Attaching the same file twice is almost always a repeated "
                f"click rather than a second document."
            )

        attachment = InvoiceAttachment(
            tenant_id=invoice.tenant_id,
            invoice=invoice,
            original_filename=(upload.name or "file")[:255],
            content_type=(upload.content_type or "").split(";")[0].strip()[:100],
            size_bytes=upload.size,
            sha256=sha256,
            description=body.validated_data.get("description", ""),
            uploaded_by_id=getattr(request.user, "id", None),
            created_by_id=getattr(request.user, "id", None),
        )
        # Assigned after construction so `invoice_attachment_path` can read
        # tenant_id and invoice_id off the instance to build the key.
        attachment.file = upload
        attachment.save()

        return Response(
            InvoiceAttachmentSerializer(
                attachment, context=self.get_serializer_context()
            ).data,
            status=status.HTTP_201_CREATED,
        )


    # -- generated transitions ---------------------------------------------
    # ``url_path`` is passed explicitly on every one of these: without it the
    # generated handler is named ``transition`` and DRF would mount all three
    # at the same URL.

    issue = transition_action(
        "apps.sales.services.invoice_workflow.issue_invoice",
        url_path="issue",
    )

    void = transition_action(
        "apps.sales.services.invoice_workflow.void_invoice",
        url_path="void",
        body_serializer=ReasonRequiredTransitionSerializer,
        pass_reason=True,
    )

    write_off = transition_action(
        "apps.sales.services.invoice_workflow.write_off_invoice",
        url_path="write-off",
        body_serializer=WriteOffInputSerializer,
        pass_reason=True,
        build_kwargs=lambda view, instance, payload: {
            "write_off_date": payload.get("write_off_date")
        },
    )

    # -- hand-written actions ----------------------------------------------

    @action(detail=True, methods=["post"], url_path="send-reminder")
    def send_reminder(self, request, pk=None):
        """Queue a dunning reminder for this invoice.

        Writes a :class:`~apps.sales.models.PaymentReminderLog` row in PENDING
        and returns 202; it does not send anything inline. Sending inside the
        request would mean an SMTP or SMS provider's latency is the user's
        latency, and a provider timeout would leave the caller unable to tell
        whether the customer was contacted — so they would click again, and the
        customer would be chased twice for the same invoice.

        The log row is written *before* dispatch for the same reason the
        webhook receiver stores before processing: a crash between "sent" and
        "recorded" produces a duplicate on the next run, and a customer chased
        twice in one day is a complaint. ``(invoice, rule, scheduled_for)`` is
        the dedup key, which is why extending a due date legitimately allows
        the same rule to fire again.

        Refused for invoices with nothing outstanding. Chasing a paid invoice
        is the single fastest way to make a tenant distrust the whole module.
        """
        invoice = self.get_object()
        body = SendReminderInputSerializer(data=request.data)
        body.is_valid(raise_exception=True)

        if invoice.status not in OPEN_INVOICE_STATUSES:
            raise DomainError(
                f"Invoice {invoice.number or invoice.id} is "
                f"{invoice.get_status_display().lower()} and has nothing "
                f"outstanding to chase."
            )

        rule_id = body.validated_data.get("rule")
        rules = PaymentReminderRule.objects.filter(is_active=True)
        rule = rules.filter(pk=rule_id).first() if rule_id else rules.order_by(
            "offset_days"
        ).first()
        if rule is None:
            raise DomainError(
                "No active payment reminder rule is configured. Create one "
                "before sending reminders, so the wording and the channel are a "
                "tenant decision rather than a hard-coded default."
            )

        if (invoice.amount_due or ZERO) < (rule.minimum_amount_due or ZERO):
            raise DomainError(
                f"Invoice {invoice.number} owes {invoice.amount_due} "
                f"{invoice.currency}, below rule '{rule.name}'s minimum of "
                f"{rule.minimum_amount_due}. Chasing it costs more than it "
                f"collects."
            )

        from datetime import timedelta

        scheduled_for = invoice.due_date + timedelta(days=rule.offset_days)

        def run(_key: Optional[str]) -> PaymentReminderLog:
            log, created = PaymentReminderLog.objects.get_or_create(
                invoice=invoice,
                rule=rule,
                scheduled_for=scheduled_for,
                defaults={
                    "tenant_id": invoice.tenant_id,
                    "channel": rule.channel,
                    "recipient": invoice.customer.email,
                    "status": PaymentReminderLog.Status.PENDING,
                    "amount_due_snapshot": invoice.amount_due,
                    "created_by_id": getattr(request.user, "id", None),
                },
            )
            if not created:
                logger.info(
                    "reminder already logged for invoice=%s rule=%s scheduled=%s",
                    invoice.id, rule.id, scheduled_for,
                )
            return log

        result = run(None)
        return Response(
            {
                "id": str(result.id),
                "invoice": str(invoice.id),
                "rule": str(rule.id),
                "channel": result.channel,
                "recipient": result.recipient,
                "scheduled_for": result.scheduled_for.isoformat(),
                "status": result.status,
                "detail": (
                    "Reminder queued. Delivery is asynchronous; poll the "
                    "reminder log for the outcome."
                ),
            },
            status=status.HTTP_202_ACCEPTED,
        )

    @action(detail=True, methods=["get"], url_path="pdf")
    def pdf(self, request, pk=None):
        """``GET /invoices/{id}/pdf`` — **not implemented**.

        Mounted so the route exists in the schema and the frontend can be built
        against it. A real implementation renders from a *stored* snapshot of
        the invoice as issued, not from the live rows: an invoice PDF is the
        document the customer received, and re-rendering it from current data
        silently produces a different document if anything downstream changed —
        a renamed customer, a re-coded account, a corrected tax rate. The
        rendered bytes are then stored and served, so the same request always
        returns the same file.
        """
        self.get_object()
        raise NotImplementedYet(
            "Invoice PDF rendering is not implemented yet. It must render from "
            "a stored snapshot of the invoice as issued and cache the result, "
            "so that re-fetching the PDF of a historical invoice cannot return "
            "a document different from the one the customer received."
        )

    @action(detail=True, methods=["get"], url_path="journal-entry")
    def journal_entry(self, request, pk=None):
        """The journal entry this invoice posted when it was issued.

        The link the auditor follows from a document to its ledger effect. A
        draft invoice has none — that is not an error, it is the definition of
        a draft — so it answers 404 with a message saying so rather than an
        empty body the client has to guess at.
        """
        from rest_framework.exceptions import NotFound

        from apps.accounting.serializers import JournalEntrySerializer

        invoice = self.get_object()
        if invoice.journal_entry_id is None:
            raise NotFound(
                f"Invoice {invoice.number or invoice.id} has not been issued, so "
                f"it has no journal entry. Nothing is posted to the ledger until "
                f"POST /invoices/{{id}}/issue succeeds."
            )
        return Response(
            JournalEntrySerializer(
                invoice.journal_entry, context=self.get_serializer_context()
            ).data
        )


# ---------------------------------------------------------------------------
# Credit notes and automation
# ---------------------------------------------------------------------------

class CreditNoteViewSet(TenantModelViewSet):
    """Credit notes: the document that reduces what a customer owes."""

    permission_domain = "sales"
    resource = "credit_note"
    queryset = CreditNote.objects.all()
    serializer_class = CreditNoteSerializer
    select_related = ("customer", "invoice", "journal_entry")
    prefetch_related = ("lines",)
    filterset_fields = ("status", "customer", "invoice", "currency", "issue_date")
    search_fields = ("number", "reason", "customer__name")
    ordering_fields = ("issue_date", "number", "total_amount")
    ordering = ("-issue_date", "-number")
    extra_permissions = {
        "issue": ["sales.credit_note.issue"],
        "apply": ["sales.credit_note.apply"],
    }


class RecurringInvoiceProfileViewSet(TenantModelViewSet):
    """Schedules that generate invoices."""

    permission_domain = "sales"
    resource = "recurring_profile"
    queryset = RecurringInvoiceProfile.objects.all()
    serializer_class = RecurringInvoiceProfileSerializer
    select_related = ("customer", "project")
    pagination_class = SmallPagePagination
    filterset_fields = ("is_active", "customer", "frequency", "auto_send")
    search_fields = ("name", "customer__name")
    ordering_fields = ("name", "next_run_date", "start_date")
    ordering = ("name",)
    extra_permissions = {
        "create": ["sales.recurring_profile.manage"],
        "update": ["sales.recurring_profile.manage"],
        "partial_update": ["sales.recurring_profile.manage"],
        "run_now": ["sales.recurring_profile.run_now"],
    }


class PaymentReminderRuleViewSet(TenantModelViewSet):
    """Dunning rules.

    Guarded by the ``sales.invoice`` permissions rather than a resource of its
    own: ``config/permissions.json`` has no ``reminder_rule`` resource, and a
    codename invented here would be one nobody can ever hold, because
    ``HasPermission`` denies anything absent from the catalogue. Writing a
    dunning rule is in practice the same authority as sending an invoice.
    """

    permission_domain = "sales"
    resource = "invoice"
    scope_resource = "invoice"
    queryset = PaymentReminderRule.objects.all()
    serializer_class = PaymentReminderRuleSerializer
    pagination_class = SmallPagePagination
    filterset_fields = ("is_active", "channel", "notify_internal_only")
    search_fields = ("name", "template_subject")
    ordering_fields = ("offset_days", "name")
    ordering = ("offset_days",)
    extra_permissions = {
        "create": ["sales.invoice.send"],
        "update": ["sales.invoice.send"],
        "partial_update": ["sales.invoice.send"],
    }

    def get_queryset(self):
        # ``PaymentReminderRule`` is configuration, not a scoped document: the
        # ABAC scope for ``invoice`` filters on ``created_by``/``project``,
        # columns this model does not have. Bypassing the scope narrowing (but
        # not the tenant manager) is deliberate and confined to this class.
        queryset = PaymentReminderRule.objects.all()
        if self.ordering:
            queryset = queryset.order_by(*self.ordering)
        return queryset


__all__ = [
    "CustomerViewSet",
    "InvoiceViewSet",
    "CreditNoteViewSet",
    "RecurringInvoiceProfileViewSet",
    "PaymentReminderRuleViewSet",
    "WriteOffInputSerializer",
    "SendReminderInputSerializer",
]


class InvoiceAttachmentViewSet(TenantModelViewSet):
    """Files attached to an invoice.

    Listing and deleting live here; *uploading* is an action on the invoice
    (``POST /invoices/{id}/attachments/``), because the file only means
    anything in the context of the document it belongs to and a top-level
    create would need the invoice id in the body anyway.

    Permissioned as ``sales.invoice.update``: attaching or removing evidence
    changes what the invoice says, so anyone who may not edit the invoice may
    not edit its attachments either.

    Unlike most documents here, attachments **can** be hard-deleted. They are
    not financial records — nothing in the ledger references them, no total
    changes — and an evidence file uploaded in error (the wrong customer's
    contract) is a document that must actually go, not one that lingers
    archived. The invoice's own immutability is untouched.
    """

    permission_domain = "sales"
    resource = "invoice"
    scope_resource = "invoice"
    queryset = InvoiceAttachment.objects.all()
    serializer_class = InvoiceAttachmentSerializer
    select_related = ("invoice", "uploaded_by")
    pagination_class = SmallPagePagination
    filterset_fields = ("invoice",)
    ordering_fields = ("created_at", "size_bytes")
    ordering = ("-created_at",)
    extra_permissions = {
        "DELETE": ["sales.invoice.update"],
        "PATCH": ["sales.invoice.update"],
    }

    def destroy(self, request, *args, **kwargs):
        """Remove the row *and* the bytes.

        ``TenantModelViewSet.destroy`` refuses on principle, so this overrides
        it deliberately — see the class docstring for why an attachment is not
        a financial record. The stored file is deleted after the row so that a
        failure leaves an orphaned blob (recoverable, costs storage) rather
        than a row pointing at bytes that are gone (a broken download nobody
        can explain).
        """
        attachment = self.get_object()
        stored = attachment.file
        attachment.delete()
        try:
            stored.delete(save=False)
        except Exception:  # noqa: BLE001 - the row is already gone
            logger.warning(
                "attachment row deleted but its file could not be removed: %s",
                stored.name, exc_info=True,
            )
        return Response(status=status.HTTP_204_NO_CONTENT)
