# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.core.fields
import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("inventory", "0001_initial"),
        ("projects", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                (
                    "name",
                    models.CharField(
                        help_text="Legal name for tax documents.", max_length=255
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Trading name shown in the UI.",
                        max_length=255,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                ("billing_address", models.JSONField(blank=True, default=dict)),
                ("shipping_address", models.JSONField(blank=True, default=dict)),
                ("payment_terms_days", models.PositiveSmallIntegerField(default=30)),
                (
                    "credit_limit",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("has_credit_limit", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        help_text="AR control account this customer's balance rolls up to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_customers",
                        to="accounting.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_customer",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("issue_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("exchange_rate", apps.core.fields.RateField(default=1)),
                (
                    "subtotal_amount",
                    apps.core.fields.MoneyField(
                        default=Decimal("0.000000"),
                        help_text="Sum of line subtotals, before tax.",
                    ),
                ),
                (
                    "discount_amount",
                    apps.core.fields.MoneyField(
                        default=Decimal("0.000000"),
                        help_text="Header-level discount, deducted from subtotal_amount.",
                    ),
                ),
                (
                    "tax_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "total_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "amount_paid",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "amount_due",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("partially_paid", "Partially paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("voided", "Voided"),
                            ("written_off", "Written off"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Shown to the customer."),
                ),
                (
                    "terms",
                    models.TextField(
                        blank=True, help_text="Payment terms boilerplate."
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                ("written_off_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="sales.customer",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="projects.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_invoice",
                "ordering": ["-issue_date", "-number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("issue_date", models.DateField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("exchange_rate", apps.core.fields.RateField(default=1)),
                (
                    "subtotal_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "tax_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "total_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "amount_applied",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "amount_remaining",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("applied", "Fully applied"),
                            ("voided", "Voided"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="sales.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="sales.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "sales_credit_note",
                "ordering": ["-issue_date", "-number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveSmallIntegerField()),
                ("description", models.CharField(max_length=500)),
                ("quantity", apps.core.fields.QuantityField(default=1)),
                (
                    "unit_price",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "discount_rate",
                    apps.core.fields.RateField(default=Decimal("0.000000")),
                ),
                (
                    "line_subtotal",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("line_tax", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "line_total",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "income_account",
                    models.ForeignKey(
                        help_text="Revenue account this line credits.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="accounting.account",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for free-text service lines.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="projects.project",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for out-of-scope / exempt lines.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="accounting.taxrate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_invoice_line",
                "ordering": ["invoice", "line_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditNoteLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveSmallIntegerField()),
                ("description", models.CharField(max_length=500)),
                ("quantity", apps.core.fields.QuantityField(default=1)),
                (
                    "unit_price",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "discount_rate",
                    apps.core.fields.RateField(default=Decimal("0.000000")),
                ),
                (
                    "line_subtotal",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("line_tax", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "line_total",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("restocks_inventory", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.creditnote",
                    ),
                ),
                (
                    "income_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note_lines",
                        to="accounting.account",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note_lines",
                        to="projects.project",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note_lines",
                        to="accounting.taxrate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note_lines",
                        to="sales.invoiceline",
                    ),
                ),
            ],
            options={
                "db_table": "sales_credit_note_line",
                "ordering": ["credit_note", "line_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentReminderRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "offset_days",
                    models.SmallIntegerField(
                        help_text="Negative = days before due date, positive = days after."
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("template_subject", models.CharField(blank=True, max_length=255)),
                (
                    "template_body",
                    models.TextField(
                        help_text="Rendered with the invoice, customer and tenant in context."
                    ),
                ),
                (
                    "minimum_amount_due",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notify_internal_only", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_payment_reminder_rule",
                "ordering": ["offset_days"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentReminderLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_for", models.DateField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=10,
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "amount_due_snapshot",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminder_logs",
                        to="sales.invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="sales.paymentreminderrule",
                    ),
                ),
            ],
            options={
                "db_table": "sales_payment_reminder_log",
                "ordering": ["-scheduled_for"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoiceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Every two weeks"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semiannual", "Every six months"),
                            ("annual", "Annually"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("interval", models.PositiveSmallIntegerField(default=1)),
                ("start_date", models.DateField()),
                (
                    "next_run_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "max_occurrences",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("occurrences_generated", models.PositiveIntegerField(default=0)),
                ("auto_send", models.BooleanField(default=False)),
                ("payment_terms_days", models.PositiveSmallIntegerField(default=30)),
                ("lead_days", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_profiles",
                        to="sales.customer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_profiles",
                        to="projects.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_recurring_invoice_profile",
                "ordering": ["next_run_date", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoiceLineTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveSmallIntegerField()),
                ("description", models.CharField(max_length=500)),
                ("quantity", apps.core.fields.QuantityField(default=1)),
                (
                    "unit_price",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "discount_rate",
                    apps.core.fields.RateField(default=Decimal("0.000000")),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "income_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_line_templates",
                        to="accounting.account",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_line_templates",
                        to="inventory.item",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_line_templates",
                        to="accounting.taxrate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_templates",
                        to="sales.recurringinvoiceprofile",
                    ),
                ),
            ],
            options={
                "db_table": "sales_recurring_invoice_line_template",
                "ordering": ["profile", "line_number"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="recurring_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this invoice was generated from a schedule.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_invoices",
                to="sales.recurringinvoiceprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "-created_at"], name="sales_custo_tenant__0aca54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "is_active"], name="ix_customer_active"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "name"], name="ix_customer_name"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "email"], name="ix_customer_email"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_customer_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_limit__gte", 0)),
                name="ck_customer_credit_limit_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(
                fields=["tenant", "-created_at"], name="sales_credi_tenant__d574b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(
                fields=["tenant", "status", "issue_date"], name="ix_cn_status"
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(fields=["tenant", "customer"], name="ix_cn_customer"),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(fields=["tenant", "invoice"], name="ix_cn_invoice"),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("tenant", "number"),
                name="uq_credit_note_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "amount_remaining",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total_amount"), "-", models.F("amount_applied")
                        ),
                    )
                ),
                name="ck_credit_note_remaining_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal_amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("total_amount__gte", 0),
                    ("amount_applied__gte", 0),
                ),
                name="ck_credit_note_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_applied__lte", models.F("total_amount"))),
                name="ck_credit_note_no_over_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "draft"),
                    models.Q(("number", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_credit_note_issued_has_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="ck_credit_note_fx_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["tenant", "-created_at"], name="sales_invoi_tenant__c09a94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["invoice", "line_number"], name="ix_invoice_line_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(fields=["tenant", "item"], name="ix_invoice_line_item"),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["tenant", "project"], name="ix_invoice_line_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.UniqueConstraint(
                fields=("invoice", "line_number"), name="uq_invoice_line_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0), ("unit_price__gte", 0)),
                name="ck_invoice_line_qty_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_rate__gte", 0), ("discount_rate__lte", 1)
                ),
                name="ck_invoice_line_discount_fraction",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("line_subtotal__gte", 0),
                    ("line_tax__gte", 0),
                    ("line_total__gte", 0),
                ),
                name="ck_invoice_line_amounts_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="creditnoteline",
            index=models.Index(
                fields=["tenant", "-created_at"], name="sales_credi_tenant__8e0e25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditnoteline",
            index=models.Index(
                fields=["credit_note", "line_number"], name="ix_cn_line_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="creditnoteline",
            index=models.Index(fields=["tenant", "item"], name="ix_cn_line_item"),
        ),
        migrations.AddConstraint(
            model_name="creditnoteline",
            constraint=models.UniqueConstraint(
                fields=("credit_note", "line_number"), name="uq_credit_note_line_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0), ("unit_price__gte", 0)),
                name="ck_cn_line_qty_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_rate__gte", 0), ("discount_rate__lte", 1)
                ),
                name="ck_cn_line_discount_fraction",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("line_subtotal__gte", 0),
                    ("line_tax__gte", 0),
                    ("line_total__gte", 0),
                ),
                name="ck_cn_line_amounts_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreminderrule",
            index=models.Index(
                fields=["tenant", "-created_at"], name="sales_payme_tenant__0edbc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreminderrule",
            index=models.Index(
                fields=["tenant", "is_active"], name="ix_reminder_rule_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentreminderrule",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_reminder_rule_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentreminderrule",
            constraint=models.UniqueConstraint(
                fields=("tenant", "offset_days", "channel"),
                name="uq_reminder_rule_offset_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentreminderrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_amount_due__gte", 0)),
                name="ck_reminder_rule_min_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreminderlog",
            index=models.Index(
                fields=["tenant", "-created_at"], name="sales_payme_tenant__237f63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreminderlog",
            index=models.Index(
                fields=["tenant", "status", "scheduled_for"], name="ix_reminder_log_due"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreminderlog",
            index=models.Index(fields=["invoice"], name="ix_reminder_log_invoice"),
        ),
        migrations.AddConstraint(
            model_name="paymentreminderlog",
            constraint=models.UniqueConstraint(
                fields=("invoice", "rule", "scheduled_for"),
                name="uq_reminder_log_dedup",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentreminderlog",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_due_snapshot__gte", 0)),
                name="ck_reminder_log_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentreminderlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "sent"), _negated=True),
                    ("sent_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_reminder_log_sent_has_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvoiceprofile",
            index=models.Index(
                fields=["tenant", "-created_at"], name="sales_recur_tenant__5ba59d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvoiceprofile",
            index=models.Index(
                fields=["tenant", "customer"], name="ix_recurring_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvoiceprofile",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["next_run_date"],
                name="ix_recurring_due",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoiceprofile",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_recurring_profile_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoiceprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="ck_recurring_profile_date_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoiceprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval__gte", 1)),
                name="ck_recurring_profile_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoiceprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_active", False),
                    ("next_run_date__isnull", False),
                    _connector="OR",
                ),
                name="ck_recurring_profile_active_has_next_run",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvoicelinetemplate",
            index=models.Index(
                fields=["tenant", "-created_at"], name="sales_recur_tenant__3ae215_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvoicelinetemplate",
            index=models.Index(
                fields=["profile", "line_number"], name="ix_recurring_line_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoicelinetemplate",
            constraint=models.UniqueConstraint(
                fields=("profile", "line_number"), name="uq_recurring_line_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoicelinetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0), ("unit_price__gte", 0)),
                name="ck_recurring_line_qty_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoicelinetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_rate__gte", 0), ("discount_rate__lte", 1)
                ),
                name="ck_recurring_line_discount_fraction",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "-created_at"], name="sales_invoi_tenant__6533d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "status", "due_date"], name="ix_invoice_status"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "customer", "status"], name="ix_invoice_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "issue_date"], name="ix_invoice_issue_date"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["tenant", "project"], name="ix_invoice_project"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                condition=models.Q(("amount_due__gt", 0)),
                fields=["tenant", "due_date"],
                name="ix_invoice_open_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("tenant", "number"),
                name="uq_invoice_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "amount_due",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total_amount"), "-", models.F("amount_paid")
                        ),
                    )
                ),
                name="ck_invoice_due_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal_amount__gte", 0),
                    ("discount_amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("total_amount__gte", 0),
                    ("amount_paid__gte", 0),
                ),
                name="ck_invoice_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_amount",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("subtotal_amount"),
                                "-",
                                models.F("discount_amount"),
                            ),
                            "+",
                            models.F("tax_amount"),
                        ),
                    )
                ),
                name="ck_invoice_total_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__lte", models.F("total_amount"))),
                name="ck_invoice_no_overpayment",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_date__gte", models.F("issue_date"))),
                name="ck_invoice_due_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="ck_invoice_fx_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "draft"),
                    models.Q(("number", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_invoice_issued_has_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "voided"), _negated=True),
                    models.Q(("void_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_invoice_void_has_reason",
            ),
        ),
    ]
