# Generated by Django 5.2.17 on 2026-08-17 14:50

import apps.banking.models
import apps.core.fields
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("bank_name", models.CharField(max_length=120)),
                ("account_number_last4", models.CharField(blank=True, max_length=4)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("swift", models.CharField(blank=True, max_length=11)),
                ("branch", models.CharField(blank=True, max_length=120)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "opening_balance",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("opening_date", models.DateField(blank=True, null=True)),
                (
                    "current_balance",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                ("balance_as_of", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "feed_provider",
                    models.CharField(
                        choices=[
                            ("none", "Manual import only"),
                            ("plaid", "Plaid"),
                            ("saltedge", "Salt Edge"),
                            ("tink", "Tink"),
                            ("yodlee", "Yodlee"),
                            ("direct", "Direct bank API"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("feed_external_id", models.CharField(blank=True, max_length=128)),
                ("feed_last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "banking_bank_account",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement_number", models.CharField(blank=True, max_length=50)),
                ("statement_date", models.DateField(db_index=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "opening_balance",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "closing_balance",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "import_source",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("ofx", "OFX / QFX"),
                            ("mt940", "SWIFT MT940"),
                            ("camt053", "ISO 20022 CAMT.053"),
                            ("api", "Bank API feed"),
                            ("manual", "Manual entry"),
                        ],
                        default="csv",
                        max_length=10,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_checksum", models.CharField(blank=True, max_length=64)),
                ("line_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "banking_bank_statement",
                "ordering": ["-statement_date", "-imported_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField(db_index=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("reference", models.CharField(blank=True, max_length=140)),
                ("counterparty_name", models.CharField(blank=True, max_length=200)),
                ("counterparty_account", models.CharField(blank=True, max_length=64)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount", apps.core.fields.MoneyField(default=Decimal("0.000000"))),
                (
                    "running_balance",
                    apps.core.fields.MoneyField(
                        blank=True, default=Decimal("0.000000"), null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched"),
                            ("suggested", "Match suggested"),
                            ("matched", "Matched"),
                            ("ignored", "Ignored"),
                            ("manual", "Manually posted"),
                        ],
                        db_index=True,
                        default="unmatched",
                        max_length=10,
                    ),
                ),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "db_table": "banking_bank_transaction",
                "ordering": ["-transaction_date", "-created_at"],
                "abstract": False,
            },
            bases=(apps.banking.models.StatusTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReconciliationMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "matched_amount",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("auto_exact", "Automatic — exact"),
                            ("auto_fuzzy", "Automatic — fuzzy"),
                            ("manual", "Manual"),
                            ("split", "Split / partial"),
                            ("rule", "Rule-based"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("confidence_score", apps.core.fields.RateField(default=1)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "banking_reconciliation_match",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReconciliationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EGP", "Egyptian Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound Sterling"),
                            ("SAR", "Saudi Riyal"),
                            ("AED", "UAE Dirham"),
                            ("KWD", "Kuwaiti Dinar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "statement_closing_balance",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "ledger_closing_balance",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "difference",
                    apps.core.fields.MoneyField(default=Decimal("0.000000")),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("balanced", "Balanced, awaiting sign-off"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=12,
                    ),
                ),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("unmatched_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "banking_reconciliation_session",
                "ordering": ["-period_end"],
                "abstract": False,
            },
            bases=(apps.banking.models.StatusTransitionMixin, models.Model),
        ),
    ]
