# Generated by Django 5.2.17 on 2026-08-17 14:50

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("banking", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="ledger_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_account",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statements",
                to="banking.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="imported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="banking.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="matched_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="statement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="banking.bankstatement",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationmatch",
            name="bank_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="banking.banktransaction",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationmatch",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationmatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationmatch",
            name="journal_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_matches",
                to="accounting.journalline",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationmatch",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationmatch",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationsession",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliations",
                to="banking.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationsession",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationsession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationsession",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationsession",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationmatch",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="banking.reconciliationsession",
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["tenant", "-created_at"], name="banking_ban_tenant__66d026_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["tenant", "is_active"], name="ix_bank_account_active"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["tenant", "feed_provider"], name="ix_bank_account_feed"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_bank_account_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("iban", ""), _negated=True),
                fields=("tenant", "iban"),
                name="uq_bank_account_iban",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("feed_external_id", ""), _negated=True),
                fields=("tenant", "feed_provider", "feed_external_id"),
                name="uq_bank_account_feed_id",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatement",
            index=models.Index(
                fields=["tenant", "-created_at"], name="banking_ban_tenant__04f138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatement",
            index=models.Index(
                fields=["tenant", "bank_account", "statement_date"],
                name="ix_bank_statement_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("file_checksum", ""), _negated=True),
                fields=("tenant", "file_checksum"),
                name="uq_bank_statement_checksum",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statement_number", ""), _negated=True),
                fields=("tenant", "bank_account", "statement_number"),
                name="uq_bank_statement_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period_end__isnull", True),
                    ("period_start__isnull", True),
                    ("period_end__gte", models.F("period_start")),
                    _connector="OR",
                ),
                name="ck_bank_statement_period_order",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["tenant", "-created_at"], name="banking_ban_tenant__479794_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["tenant", "bank_account", "status", "transaction_date"],
                name="ix_bank_txn_worklist",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["tenant", "transaction_date"], name="ix_bank_txn_date"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["tenant", "bank_account", "amount"], name="ix_bank_txn_amount"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["tenant", "statement"], name="ix_bank_txn_statement"
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("tenant", "bank_account", "external_id"),
                name="uq_bank_txn_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="ck_bank_txn_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "matched"), _negated=True),
                    ("matched_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_bank_txn_matched_at",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationsession",
            index=models.Index(
                fields=["tenant", "-created_at"], name="banking_rec_tenant__02c057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationsession",
            index=models.Index(
                fields=["tenant", "bank_account", "status"],
                name="ix_recon_session_account",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationsession",
            index=models.Index(
                fields=["tenant", "period_end"], name="ix_recon_session_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationsession",
            constraint=models.UniqueConstraint(
                fields=("tenant", "bank_account", "period_start", "period_end"),
                name="uq_recon_session_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="ck_recon_session_date_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "closed"), _negated=True),
                    ("difference", 0),
                    _connector="OR",
                ),
                name="ck_recon_session_closed_balanced",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "closed"), _negated=True),
                    models.Q(
                        ("closed_at__isnull", False), ("closed_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_recon_session_closed_signoff",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "difference",
                        django.db.models.expressions.CombinedExpression(
                            models.F("statement_closing_balance"),
                            "-",
                            models.F("ledger_closing_balance"),
                        ),
                    )
                ),
                name="ck_recon_session_difference",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationmatch",
            index=models.Index(
                fields=["tenant", "-created_at"], name="banking_rec_tenant__485414_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationmatch",
            index=models.Index(
                fields=["tenant", "bank_transaction"], name="ix_recon_match_txn"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationmatch",
            index=models.Index(
                fields=["tenant", "journal_line"], name="ix_recon_match_line"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationmatch",
            index=models.Index(
                fields=["tenant", "session"], name="ix_recon_match_session"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationmatch",
            index=models.Index(
                fields=["tenant", "match_type"], name="ix_recon_match_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationmatch",
            constraint=models.UniqueConstraint(
                fields=("bank_transaction", "journal_line"),
                name="uq_reconciliation_match_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("matched_amount__gt", 0)),
                name="ck_reconciliation_match_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence_score__gte", 0), ("confidence_score__lte", 1)
                ),
                name="ck_reconciliation_confidence_range",
            ),
        ),
    ]
